### ISSUE TITLE
Request: option for shorter UUIDs

### ISSUE THREAD

**Issue by okapia** [iocage/iocage#10]
I'm looking into whether to migrate from ezjail and, while perhaps just a trivial thing, what bothers me most is the use of 36 character UUIDs as jail names. This causes zfs list output to overflow the width of even a fairly wide terminal. The documentation doesn't even make it clear what the technical purpose of these UUIDs is. Do they really need to be so long as to ensure global uniqueness - and they are much longer than would be needed to ensure that. Thanks

**Comment by skarekrow** [comment]
I can understand the frustration as this doesn't have any documentation yet, so let me explain.

36 characters is a very standard length for UUID's and yes are absolutely needed to maintain uniqueness, without an arbitrary cap of jails because of my chosen length. In addition we support tags, which are human readable names that you the user assigns. Every operation supports them, and I encourage using them if you haven't explored the concept. In addition we also support short uuid support for every command, so you can type as few as 1 character to match a jail if there isn't anything else conflicting. 

If you use tags, we have them all at `/iocage/tags/TAG`, so you can easily `cd` into that directory or whatever else you require. Also, you aren't meant to use `zfs list` if you wish to get a UUID, there are a few methods we help you with.

1 - `iocage get host_hostuuid TAG`
2 - `iocage list -l` (this gives you a long list, with 36 character UUID's.
3 - `iocage list` (this gives you a short 8 character UUID and less information.

Option 1 can be used on the terminal to ease operations:
 ```
cd /iocage/jails/`iocage get host_hostuuid TAG`
```

Hopefully this all helps explain why we use UUIDs and how as a user working with them doesn't need to be frustrating. We have many mechanisms that ease that burden. I usually work with a terminal of 142x80, which helps if I'm using zfs with the UUIDs, which is not terribly wide. Unless you're using serial ofcourse, then I'd look into those other methods I explained above. Thanks for the question, I hope you choose to migrate!

**Comment by okapia** [comment]
Thanks for the answer.

For what it's worth, I wasn't suggesting that I use `zfs list` to get a UUID. I use `zfs list` for the purpose it was designed. Most of my filesystems have short names. If I resize my terminal to the full width of my screen it is 136 wide and the iocage /root still wraps. But the bigger problem is that it is very hard to visually line up the short zfs filesystem's names with the corresponding USED/AVAIL columns because there is too much space separating them.

Is there some other approach that might work: perhaps using the tag for the zfs filesystem and having symlinks for the UUIDs?

What actual functionality does a UUID enable? ezjail had it's issues but it worked without them so what is it missing by not having them?

Thanks

**Comment by skarekrow** [comment]
Oh my bad, I misinterpreted the question. 

We use UUID's to help guarantee no collisions. It's a system we've used for a few years now and has worked well for us. I assume you want to migrate from ezjail precisely because we aren't ezjail right? :P 

I'm not terribly familiar with how Dirk's software works, but I know that ours uses UUIDs for large deployments. I have a few friends (@sean- is one who springs to mind) who love the fact we use them. They don't care about tags, but just the UUIDs and it lets them operate quite quickly. Tags are a compromise for the average user or anybody who has a deployment where that setup works nicely.

The only case where we use the tag for the zfs dataset is templates, and even then you can reference them by UUID. When you don't supply a tag to iocage, we automatically create one as the date. So you can imagine trying to suss out all the dates would get quite irritating. Even if you change a tag, the UUID is always consistent. So you can script once, and no matter what you decide to rename the jail to later on, that script will keep working. UUIDs pose many benefits, and only a couple negatives.

The first negative is what you have noted, and the second negative is a FreeBSD issue where we can't go into directories over 80 characters in length. That's why we have the `/iocage/tags` filesystem to begin with. When FreeBSD fixes that issue (they may have already, I haven't tested for sometime) I don't see a compelling reason to not use UUIDs at all.

Hopefully this helps, and I'm sorry that it causes these slight irritants for you.

Thanks!

**Comment by sean-** [comment]
If you want to use tags, use them as a lookup mechanism to find a unique UUID.  But at the end of the day tags do not provide identity, only UUIDs do (or some other guaranteed unique identifier like a globally shared monotonic integer).  See `nomadproject.io` for an example.

**Comment by skarekrow** [comment]
@okapia doing a small smokescreen test right now on a change for you. It will make UUID's 8 characters if you supply `-s` or `--short` to create. Everything seems to be fine, so please report any bugs you find with it! 👍

**Comment by sean-** [comment]
@skarekrow One thing we do that may be useful here is we load the full UUID into memory and then do a prefix search on the supplied UUID and if the supplied UUID uniquely resolves to a single full UUID, we accept the shortened user-supplied UUID (prefix search in a radix tree).  Food for thought.

**Comment by skarekrow** [comment]
@sean- I do something similar with the regex engine for input. It can resolve as few as one characters. But this change is instead truncating the actual UUID for the dataset, it shouldn't pose any issues beyond the collisions I spoke about earlier I believe.

@okapia https://github.com/iocage/iocage/commit/14f4b21dda97c54ea69f1187ef3576a886794bb5 it's been pushed :) Please test and report back! 

Thanks for the suggestion.

**Comment by okapia** [comment]
Thank you very much!
I've installed and all seems fine so far. Will let you know if I find any issues.

**Comment by skarekrow** [comment]
Awesome!
