### ISSUE TITLE
`iocage console` is broken.

### ISSUE THREAD

**Issue by skarekrow** [iocage/iocage#100]
Somewhere along the line we broke ```iocage console```. The error is:

jexec: execvp(): login: No such file or directory

**Comment by pannon** [comment]
Works for me.

**Comment by skarekrow** [comment]
Hm. I tried with the latest master and it didn't work for me. Does dev also work for you?

**Comment by skarekrow** [comment]
And now it works. I think something is funky with the vm.

**Comment by aduitsis** [comment]
I noticed the exact same error today in one of my jails, `jexec: execvp(): login: No such file or directory.`

As it turns out, the jail was devoid of /bin, /sbin, /usr, etc, as I noticed by looking at  `/iocage/jails/<uuid>/root/`. `zfs list` also confirmed the same. Obviously one could not ssh or console into that jail, as /bin/sh did not exist where it should.

Somewhere earlier today I had issued an `iocage update <uuid>` while the jail was live, that's it. Something must have gone wrong, but I really cannot figure out what, cannot rule out a bug in iocage either. The type of that uuid was `jail` and, if memory serves, I hadn't promoted it.

I scratched my head over this for a while before I had the inspiration to `iocage set type=basejail <uuid>`. That did it, I restarted and the base filesystem parts were recloned into the proper places.
