### ISSUE TITLE
upgrade error etcupdate failed!

### ISSUE THREAD

**Issue by w4andy** [iocage/iocage#1020]
The upgrade from older Jails (Basejail) does not work.

The Jails was create with FreeBSD 11.1 (Oct 29, 2017) then upgraded to 11.2 (Aug 13, 2018), when upgrading these Jails to 11.3 I get the error message `etcupdate failed!`.

The upgrade form the newer Jails works, this jails was created Oct  6, 2018 and later.

Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

```
# iocage --version
Version	1.2 BETA
# pkg version | grep 'iocage'
py36-iocage-devel-1.0.0.20190308,1
```

- [x] Supply the commands used, along with any steps to recreate it.
```
# iocage upgrade blackbird -r 11.3-RELEASE
```
- [x] Provide the output from the command you issued.
```
etcupdate failed! Rolling back snapshot.
```

- [x] Supply what you expected the result or output to be: upgrade the jail to 11.3 😉 

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by lubo** [comment]
Hi. I'm experiencing the same issue when trying to upgrade a basejail created with legacy iocage from 11.2-RELEASE to 12.0-RELEASE. I'm on FreeBSD 12.0-RELEASE-p10 and 784086e0c4b0c46467e8db5d5416b090a6f575bb.

@skarekrow @sonicaj Please, could you take a look?

**Comment by lubo** [comment]
`etcupdate` may invoke other apps, such as `sendmail`. Therefore, if you use 3rd party app to send emails (e.g. `ssmtp`) and you're trying to upgrade between major FreeBSD versions, you'll have to upgrade it before running `etcupdate`. Otherwise, the 3rd party app will segfault. I've no idea how to do this since you can't just do `# iocage set release=12.0-RELEASE <jail> && iocage start <jail> && iocage console <jail>` like you would with legacy iocage.

So, I ended up moving back to legacy iocage and doing (roughly):

* `# iocage set release=12.0-RELEASE <jail>`
* `# iocage start <jail>`
* `# iocage console`
  * `# pkg-static upgrade -f`
* `# iocage upgrade <jail>`

@w4andy Did something segfault in your jail too?
