### ISSUE TITLE
Documentation for upgrading iocage

### ISSUE THREAD

**Issue by ketralnis** [iocage/iocage#110]
As far as I can tell, there is currently no documentation or how-to for migrating iocage from the older shell script based system to the new Python based system. This leaves users of the older version in an odd state.

What needs documenting:

- [ ] How to update the Ports version. For instance:

```sh
$ portversion -v iocage
iocage-1.7.6                ?  error - origin not found

$ grep VERSION /usr/ports/sysutils/py-iocage/Makefile
PORTVERSION=    0.9.5
```

- [ ] How to migrate the jails themselves. It appears that the file system layout has changed, so will simply removing iocage and installing py-iocage work as expected?

- [ ] What to do if you currently have basejails, which are no longer supported (see also https://github.com/iocage/iocage/issues/50)

And probably other stuff I'm forgetting

**Comment by skarekrow** [comment]
Indeed there is documentation needed. But the good news is yes all you have to do if you were using the latest stable shell version of iocage (1.7.6) is remove iocage, install py-iocage and it will automatically do all the migration for you.

I prefer to run `iocage list` as root to do that for me. If you use `iocage-legacy`'s `develop` branch, then you will have to run `iocage migrate` once you have installed `py-iocage` and removed `iocage`.

Please don't use the `py-iocage` port, it is old and very out of date. Use `master` from GitHub, or the `py3-iocage` port.

**Comment by ketralnis** [comment]
> install `py-iocage` and it will automatically do all the migration for you. [...] Please don't use the `py-iocage` port, it is old and very out of date. Use master from GitHub, or the py3-iocage port.

Ouch, that absolutely would have been my first choice because I rely on python27 and most of the py27/py3 ports are the same code with just different python version dependencies.

That should probably be passed on to the ports maintainer (which looks like robak@FreeBSD.org) so that the port can just be deleted if it's not valid anymore.

**Comment by ketralnis** [comment]
> remove iocage, install py-iocage and it will automatically do all the migration for you.

Is that true even if the old jails are basejails?

**Comment by skarekrow** [comment]
> Is that true even if the old jails are basejails?

Yes, it should migrate those as well. If it doesn't, please make a ticket. So backups should be done first :)

> Ouch, that absolutely would have been my first choice because I rely on python27 and most of the py27/py3 ports are the same code with just different python version dependencies.<br>
That should probably be passed on to the ports maintainer (which looks like robak@FreeBSD.org) so that the port can just be deleted if it's not valid anymore.

He is aware of that, as he has been told already. I don't believe he plans on upgrading that port until FreeBSD is using Python 3 as default, which will not happen for a long time. So until that time, use `py3-iocage` as it's maintained and up-to-date with the latest release. It doesn't have a pkg yet, as FreeBSD uses Python 3.5 and I use 3.6, so until *that* _also_ gets bumped (sigh) you will have to build from ports or GitHub.
