### ISSUE TITLE
New iocage release?

### ISSUE THREAD

**Issue by adam12b1** [iocage/iocage#1139]
Currently running version 1.2, installed via pkg.

I don't know the project's criteria for generating a new release, but I wonder if it's time for one. We're dealing with https://github.com/iocage/iocage/issues/1130 (after `iocage update`, all jails have their `devfs_ruleset` property mangled and will refuse to start until it's manually reset to 4), and although the port itself is happily getting patched (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244252), that brings it up to 1.2_5. So perhaps we can get all current patches rolled into 1.2.1 or 1.3?

Thanks much.

**Comment by skarekrow** [comment]
Main project‘s direction/maintainership is now up to @sonicaj, I’m not sure his plans for a new release. But I’d imagine there is one soon.

**Comment by benjyamon** [comment]
I'm wondering if a new release might be coming out any time soon? We are experiencing the issue (https://github.com/iocage/iocage/issues/1114) of slowness, fixed in https://github.com/iocage/iocage/pull/1134 but running the FreeBSD ports version based on the latest release, which doesn't have that fix yet.
