### ISSUE TITLE
iocage removes devfs_rulesets it didn't create

### ISSUE THREAD

**Issue by kchiem** [iocage/iocage#1245]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

Version 1.2

- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
 
```
$ devfs rule showsets
1
2
3
4
9
10

$ iocage start vnet-test
No default gateway found for ipv6.
* Starting vnet-test
  vnet-test is not using the devfs_ruleset of 4, not generating a ruleset for the jail, DHCP may not work.
  + Started OK
  + Using devfs_ruleset: 9
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 192.168.0.107/20

$ iocage stop vnet-test
* Stopping vnet-test
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 9 OK
  + Removing jail process OK
  + Executing poststop OK

$ devfs rule showsets
1
2
3
4
10
```

- [x] Supply what you expected the result or output to be

I expected devfs ruleset #9 to still be there so that a subsequent start of my jail would be able to use it.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Checked iocage_lib/ioc_stop.py and I don't see any changes since the 1.2 release that would have fixed this.

**Comment by stiray** [comment]
Thank you for this, it was bugging me for whole morning, instead of setting up firewall, I was trying to make ruleset work.

And I can reproduce this issue.

There are actually hell of a lot of issues with devfs_rulesets. I am getting everything from ruleset doesnt exist (there is `devfs rule showsets` command that shows you all the rulesets, I cant understand why it wasnt used) to using ruleset 7 (probably the iocage generated) without saying the rulset 11 (that I am using) is missing. Actually I cant get a consistent behaviour and I only want to `add path pf unhide`.

I am getting frustrated with this, will just change your sources to also include pf, but devfs code needs a "refinement" or should I say, some love.
