### ISSUE TITLE
resolv.conf overwritten?

### ISSUE THREAD

**Issue by manfredu** [iocage/iocage#138]
Hi, it looks to me that iocage on FreeNAS 11 nightlies overwrites /etc/resolv.conf on every restart, although I put 
resolv_conf="/dev/null" # to prevent updating /etc/resolv.conf
in resolvconf.conf
because I want to use unbound inside that jail.

**Comment by skarekrow** [comment]
Try setting that to `none`. I believe that's what I check. Otherwise yes each run it will update resolve.conf. If that doesn't work reply back and I'll set this as a enhancement and implement it :+1:

**Comment by manfredu** [comment]
Setting resolv_conf=none didn't change anything for me.
resolv_conf="/dev/null" is set by local_unbound, so may be this should be resprected anyhow?

Something else: Is there an option to get /etc/localtime updated? By default the jails use UTC independen from waht the host is using.

**Comment by skarekrow** [comment]
I can't recall if I update localtime but I don't believe I do. File a separate issue for that and I'll mark that as an enhancement as well.

**Comment by skarekrow** [comment]
Ok all implemented @manfredu please test 👍

**Comment by manfredu** [comment]
Hi Brandon, 

iocage still copies resolv.conf from host to jail, although
/etc/resolvconf.conf in the jail contains 

resolv_conf="/dev/null" 

Regards,
Manfred 

Am 16.05.2017 20:42, schrieb Brandon Schneider: 

> Ok all implemented @manfredu [1] please test 👍 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/manfredu
[2] https://github.com/iocage/iocage/issues/138#issuecomment-301876859
[3]

**Comment by skarekrow** [comment]
@manfredu That isn't the correct syntax :)

You want to set `resolver=/dev/null` for the jail.

`iocage set resolver=/dev/null JAIL`, I confirmed works here.

**Comment by andrew-azarov** [comment]
Still not working

**Comment by andrew-azarov** [comment]
Ok years later it still happens. As soon as I reboot the jail I get my DNS prepended with # sign and  and 127.0.0.1 added as default

**Comment by Oak-Aged** [comment]
I found this page by searching "iocage resolv.conf" because after I changed my gateway and DNS IP one of my iocage jails was resetting its /etc/resolv.conf to nothing but an IP address when the jail restarts. It's the correct IP, but the "nameserver " in front of it gets deleted, and the "search <domain>" line gets deleted. I just tried the "iocage set resolver=/dev/null <jail_name>" and it worked - it now retains the correct content on a restart.

To change the gateway I used:
iocage set defaultrouter=gateway_IP jailname

And to change the DNS:
iocage set resolver=DNS_IP jailname

It worked perfectly on my other jails but not on this one. Just in case it helps: be sure that when you do the "iocage set resolver" command:
- You're not in the jail
- You're root

**Comment by henningkessler** [comment]
I have more or less a similar issue with the resolver configuration in iocage. No matter to what I set the resolver parameter, on a restart iocage overwrites the /etc/resolv.conf to an incomplete configuration which only contains the search domain but no IPs from the nameserver.

**Comment by joh-ku** [comment]
Within jails that utilize a virtualized network stack ([vnet(9)](https://www.freebsd.org/cgi/man.cgi?query=vnet&sektion=9)) and DHCP, [dhclient(8)](https://www.freebsd.org/cgi/man.cgi?query=dhclient&sektion=8) will rewrite `/etc/resolv.conf` even if `resolver=/dev/null/` has been set. However, you can create a file named `/etc/dhclient-enter-hooks` and add:

```
add_new_resolv_conf() {
        return 0
}
```

This will leave `resolv.conf` untouched, as it overwrites the default implementation of [dhclient(8)](https://www.freebsd.org/cgi/man.cgi?query=dhclient&sektion=8). See [dhclient-script(8)](https://www.freebsd.org/cgi/man.cgi?dhclient-script(8)) for details.

For further reference:
https://forums.freebsd.org/threads/forbid-dhclient-changing-resolv-conf.15283/
https://forums.freebsd.org/threads/how-to-disable-resolv-conf-re-write.48223/

**Comment by Techassi** [comment]
I can confirm this is still happening. 

Setting the resolver value via 
```shell
iocage set resolver=/dev/null <JAIL>
iocage set resolver=none <JAIL>
```
won't stop iocage from overwriting the `etc/resolv.conf` file when restarting with `iocage restart <JAIL>`.

Can we make this work instead of relying on this overload function suggested by @joh-ku above?

**Comment by andrew-azarov** [comment]
God I hate this Linuxism with dhclient.
In Linux changing your resolver is now a whole game of chance depending on which distribution you are running.
It's in sysctl and netplan and classic interfaces and sysconfig, all over the place. Why can't you leave the topmost in resolv.conf for Pete's sake?
Same with dhclient overwriting it in BSD.

I have put schg on my resolv.conf in jails to solve this permanently.
Frankly should be in RC. but iocage must make this work properly in any case.

**Comment by grembo** [comment]
> I can confirm this is still happening.
> 
> Setting the resolver value via
> 
> ```shell
> iocage set resolver=/dev/null <JAIL>
> iocage set resolver=none <JAIL>
> ```
> 
> won't stop iocage from overwriting the `etc/resolv.conf` file when restarting with `iocage restart <JAIL>`.
> 
> Can we make this work instead of relying on this overload function suggested by @joh-ku above?

I just tried and setting resolver to `/dev/null` does the trick (this is without DHCP, which is a separate story):

```
iocage set resolver=/dev/null myjail
```

This survives:
```
iocage stop myjail && iocage start myjail
iocage restart myjail
```

`none` and`/etc/resolv.conf` actually mean the same thing ([implementation](https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_start.py#L1382)).

What it _doesn't_ survive is updating the jail:

```
iocage update myjail
```
[I created a patch and a PR](1286) to change iocage's behavior when updating a jail, so that it will respect the jail's `resolver` setting.
