### ISSUE TITLE
Libgit2

### ISSUE THREAD

**Issue by cwschulz** [iocage/iocage#156]
Make sure to follow and check these boxes before submitting an issue! Thank you.
New install on Freebsd 11.0-RELEASE.  Grabbed the git repo and followed the instructions in the README.

Having issues with a version conflict between libgit2 .25.1_1, when you are expecting it to be .24.x

https://kopy.io/IDZNC - error message.

- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by skarekrow** [comment]
Yeah, the solution is to uninstall `pygit2` and `cffi` and reinstall them to use the new libgit2 library. Or install the latest version of `pygit2`. The reason iocage is locked at that version is because HardenedBSD's tree doesn't have the new libgit2 yet.

Though I'll mark this as an enhancement to do a greater or equal to check instead.
