### ISSUE TITLE
Moving basejails around

### ISSUE THREAD

**Issue by moviuro** [iocage/iocage#183]
A (huge?) value we can create is easily moving basejails around.

Since basjails basically are an application installed in a ZFS dataset, requiring a base dataset to run. If we want to move basejails around, we need:
* basejail release
* basejail required distribution sets (`base.txz`, `games.txz`, etc.)
* basejail architecture

That way, we can just take the ZFS datasets that matter (the ones that aren't cloned from a base set/release volume) and send it to an other machine with `iocage`, import the said datasets and start the jail right away. We should get:
* a fatal error if the release is not available on the new host
* a warning if only a base with a superset of the required datasets is to be found (e.g. the basejail requires `base.txz` and the only base we have has `base.txz` and `lib32.txz`)
* different warnings if architecture is different (i386 vs amd64, no idea if 32bit jails can run on 64bit host)

ATM, `export` creates a tarball of all files of a jail, be it a full jail (makes somewhat sense) or a basejail (doesn't make any sense, because, well, it doesn't need its base). If we use `zfs send` to create the archives instead, we might not even need a checksum since ZFS would, AFAICT, take care of that petty issue.

**Comment by skarekrow** [comment]
I don't understand what you are asking? A basejail is not an application inside a ZFS dataset. It is a clone of a ZFS dataset with the readonly property set. Furthermore, it uses snapshots (since that is how you need to clone) so sending it to another machine is as easy as sending the root snapshot recursively.

**Comment by moviuro** [comment]
"sending it to another machine is as easy as sending the root snapshot recursively."
Then why not do it?

**Comment by skarekrow** [comment]
Because we don't send anything currently. When that feature is in iocage, then it would certainly do so. As far as export goes, it is only using `tar` and tarring up the root of the jail. As far as it is concerned, that data *does* exist. I think there can be a nice workaround for that possibly. In the meantime, can you open a new PR with just the export request? I will be closing this one as it isn't something we want to support at this time. It's best left to the user to use `zfs send` currently.

**Comment by moviuro** [comment]
You can also leave it open for contributors to work on, instead of closing it.
It will get lost if you don't.

**Comment by skarekrow** [comment]
Sorry, I don't think you understand what I'm saying. My apologies if I wasn't clear. iocage would need to be multi-node capable for that to happen. You can't send something without the other side needing to be there open to receiving it. So that feature is irrelevant for iocage as it's meant for use on a single machine. The admin can certainly `zfs send/receive` all they wish, as that is how you would do it. We don't plan to support every edge case, and this is one of those. So when I said at this time, what I really meant was at all. This feature will not be added to iocage.
