### ISSUE TITLE
iocage fstab entries have effective maximum path length of 28 characters

### ISSUE THREAD

**Issue by atl** [iocage/iocage#186]
Make sure to follow and check these boxes before submitting an issue! Thank you.

```
# iocage --version
Version	0.9.8.1 05/23/2017
```
### This works:
```
# iocage create tag=test_positive -r 11.0-RELEASE
4da254f9-49b3-4599-924b-71f3f521db33 (test_positive) successfully created!
# iocage fstab -a test_positive "/mnt/snooker/data/nextcloud /usr/local/fairly_short_path nullfs rw 0 0"
Successfully added mount to 4da254f9-49b3-4599-924b-71f3f521db33 (test_positive)'s fstab
# iocage start test_positive
* Starting 4da254f9-49b3-4599-924b-71f3f521db33 (test_positive)
  + Started OK
  + Starting services OK
# cat /mnt/iocage/jails/4da254f9-49b3-4599-924b-71f3f521db33/fstab 
```
### This fails:
```
# iocage create tag=test_negative -r 11.0-RELEASE
b88a60e0-5a77-4906-b95b-330989ec9baa (test_negative) successfully created!
# iocage fstab -a test_negative "/mnt/snooker/data/nextcloud /usr/local/slightlylongerpath nullfs rw 0 0"
Successfully added mount to b88a60e0-5a77-4906-b95b-330989ec9baa (test_negative)'s fstab
# iocage start test_negative
* Starting b88a60e0-5a77-4906-b95b-330989ec9baa (test_negative)
  + Start FAILED
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 32, in cli
    ioc.IOCage(jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 482, in start
    callback=self.callback, silent=self.silent)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 35, in __init__
    self.__start_jail__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 258, in __start_jail__
    raise RuntimeError(f"  {stderr_data.decode('utf-8')}")
RuntimeError:   mount_nullfs: /mnt/iocage/jails/b88a60e0-5a77-4906-b95b-330989ec9baa/root/usr/local/slightlylongerpath: File name too long
jail: /sbin/mount -t nullfs -o rw /mnt/snooker/data/nextcloud /mnt/iocage/jails/b88a60e0-5a77-4906-b95b-330989ec9baa/root/usr/local/slightlylongerpath: failed
```

An effective path length of 28 characters for a `nullfs` mount is not usable in many jail applications.

**Comment by skarekrow** [comment]
This issue has more to do with FreeBSD and the limitation of 88 characters for mounts. I suggest using short uuids `iocage create -s` to get around this, there's nothing else I can do I'm afraid :(

**Comment by skarekrow** [comment]
On second thought I should atleast warn the user or something if that's the case. So marking this as an enhancement too.

**Comment by atl** [comment]
It's made more frustrating by the full 36-character UUID implicitly being added to the path. I think some communication/documentation would help.

**Comment by rwestlund** [comment]
@skarekrow Just so you know, this isn't an issue in FreeBSD 12-CURRENT.  When the ino64 project was merged a few weeks ago, the max mount path length went from 88 to 1024; it's one the the improvements they made since they were changing the ABI anyway.  Of course that will never be MFC'd, so this will be an issue for a long time.

**Comment by skarekrow** [comment]
@rwestlund Yessir I was aware, but thank you. And yes, it's certainly a ways off from being merged. So we're stuck with this problem in the meantime. 

Which opens up a question to the rest of the issue since you guys are primarily affected by this. 

What do you think about making short uuids the default and long ones the flag `-l or something` instead?

I see a lot of pros for most users, as that's still a gigantic unique namespace. They won't run into this issue and have an easier time typing them by hand.

But I also wanted the opinion of some heavier automation users like @gronke, @No9, @shivno, @jungle-boogie and @sean-  as well. 

Opinions welcomed on this!

**Comment by rwestlund** [comment]
For what it's worth, here's my perspective:

I'm not a fan of the uuid and tag system; I like having datasets with meaningful names.  I'd much prefer to generate them like `iocage create $NAME -r 11.0-RELEASE`.  If someone wants uuids, then could just do this: `iocage create $(uuidgen) -r 11.0-RELEASE`.  It's simple, flexible, and it works for everyone.  And `zfs list -r zroot/iocage/jails` could be meaningful!

For my use case, I have one jail for each of a large number of subdomains.  It would simplify my deploy/management code if I could just name each jail after the subdomain, without the tag <-> uuid mapping.

**Comment by shivno** [comment]
i totally agree with @rwestlund , when dealing with length issues i generate some short names i can understand like "zeshur-dovecot-prod-2" for servername-service-type-number. my setups are not so big i need uuids, others may prefer them :).

**Comment by skarekrow** [comment]
Interesting, I thought that way as well when I first joined the project in it's (first) shell incarnation under @pannon's stewardship. I kept UUIDs as historically we did it that way in the iocage-legacy implementation for years. I didn't want to do a knee jerk change to that implementation, as I don't think there are very many reasons to do so. I elaborated more on this in some other issue I can't recall atm, but it's in the tracker somewhere ;)

There is however more of a workaround for those who want to use the datasets from iocage in their own deployment scripts, and that's to use `/iocage/tags/TAG`, as we create a symlink to each jail. While that doesn't make `zfs list -r` anymore useful, I could extend `iocage df` to include `REFER` or perhaps a whole subcommand that replicates that functionality. I would vote to keep it in house as going underneath `iocage` to `zfs` isn't the intention, `iocage` is meant to be a one-stop kinda show. Eventually the sending bits will be ported and that should help alleviate having to use `zfs` manually for many things.

Would it make life easier on you two having short UUIDs be default? Or does that not make much a difference for you, since it's still a UUID?

**Comment by shivno** [comment]
short UUIDs wont gain anything for me. thanks for the mention.
iocage df is enough to be parsed, includes the tag. or i didnt understand it.

**Comment by rwestlund** [comment]
The ability to go underneath `iocage` to `zfs` is precisely why I like iocage so much.  I already have tools and systems in place for managing and backing up datasets; being able to snapshot and move jails and their configuration using the normal zfs toolset is iocage's best feature, IMHO.

`zfs(8)` is simple and well-designed; I don't see any benefit to having another layer on top.  Just my 2 cents.

**Comment by skarekrow** [comment]
Well I should have rephrased and said that it's my design goal, but it's not meant for the everyday user. You certainly can, and should be able to, as you currently are and that's precisely why I try mapping things the way they are.

Understandably your usecase also makes UUIDs a bit more unwieldy, perhaps I need to think on this more, if only GitHub had a voting system. Then I could find out which naming scheme people preferred to be the default. Though using TAGs as the default would mean a significant amount of retooling in the project, and it's not entirely trivial to change. So it's possible I may not end up doing just that.

**Comment by atl** [comment]
Coming as a user from SmartOS/SmartDataCenter, I get the idea behind UUIDs: instances are not pets, when thinking about the cloud. I guess the same applies to Docker/Kubernetes thinking. 

It's probably fruitful to discuss how those ecosystems map onto FreeNAS's goals.

Short UUIDs were a sufficient workaround to address my personal pain point, thanks for mentioning them on the thread.

**Comment by No9** [comment]
FWIW I prefer the current state - I am building app developer tooling and use the full UUID returned from the create to manage all further interactions. I think the **_cattle rather than pets_** approach of giving jails arbitrary names enforces some good practices but I understand how that can be a bit harsh in the scenarios above. 

I think it might be a clearer discussion if it we identified who the target end user of iocage is.
I was attracted to this project through the association with sysadm - It seemed the direction of iocage was to provide an accessible set of jails primitives with reasonable defaults to allow more simplified consumption than is currently offered in FreeBSD. 

This would then enable an ecosystem of apps to build around jails as they have in other container systems. 

The point @shivno makes here https://github.com/iocage/iocage/issues/163#issuecomment-308545064 about putting iocage in ansible rather than ansible in iocage is very well made.

**Comment by skarekrow** [comment]
I agree to a point. I'm all for including more functionality as long as it does not step on the fundamentals and introduce harder to use basics.

I think you nailed my vision for the project quite aptly, that is it's meant to simplify consumption of jails. Ideally @gronke's solution for automation is so general that it is nicer to use _and_ more practical then building a whole framework outside iocage to use it.

I'm generally quite happy with the current state of the project, it's lacking a few things I want to still port, but it's already a much better manager then it ever was, and much quicker to boot.

I definitely view jails as cattle and not pets, but it's not just about my views, which is why I reached out in this issue to garner some of the more vocal users (That's all of you <3) of my project a chance to echo back at me so we can deliberate. 

Thanks for all the opinions so far!

**Comment by skarekrow** [comment]
Even though the core issue is resolved, this conversation should continue to take place here I believe, which allows poor @atl to unsub from all the spam if they only cared about this issue being solved 👍

**Comment by atl** [comment]
(No, this is a good thread. I came to FreeNAS b/c it mapped to my personal home-server needs more than any other project, and I was already sold on the ZFS + jails approach. In my day job I see to a lot of cattle, but prefer something a little more domesticated at home.)

**Comment by rwestlund** [comment]
Thinking in terms of cattle rather than pets is good policy in many cases.  But I like the _tools, not policy_ part of the UNIX philosophy.  Policy (like naming conventions) should generally be left to sysadmin/devops.

I just discovered that there's no validation on the user-provided uuid option.  I can't believe I didn't think to check this earlier!  This works for me: `iocage create -u $NAME -r 11.0-RELEASE`.  It's a little quirky, but it does what I want: datasets with names I control.  If you intend to leave in place this [perhaps unintentional] ability to avoid uuids, then I'm happy.

I think just endorsing and documenting this is enough.  Although I'd change the API to make `name` an argument to `iocage create` and use `-u` to mean "generate a uuid name for me".  Then it would be `iocage create $NAME -r 11.0-RELEASE` or `iocage create -u -r 11.0-RELEASE`.

**Comment by skarekrow** [comment]
Totally unintended side effect of that option hahah, but hey it's there lets abuse it. I'll push some support for that soon.

The syntax will be `iocage create -n $NAME -r 11.0-RELEASE` though, as not to disturb existing functionality.
