### ISSUE TITLE
iocage complains when starting a jail with multiple network interfaces

### ISSUE THREAD

**Issue by gronke** [iocage/iocage#188]
The Jail is started either way, so everything works as expected besides the warning message.

```
iocage set ip4_addr="vnet0|192.168.1.2/32,vnet1|10.0.0.2/24" nginx
iocage set interfaces="vnet0:bridge0,vnet1:bridge1" nginx
root@freebsd11:/usr/home/fnord # iocage start nginx
* Starting dd2a6173-0a7a-4e8f-98de-6d6ad16d5dd9 (nginx)
  + Started OK

  Invalid interface supplied: vnet1
  Did you mean vnet0?


  Invalid interface supplied: vnet0
  Did you mean vnet1?


  Invalid interface supplied: vnet0
  Did you mean vnet1?

  + Starting services OK
```

Iocage Version: `0.9.9-ALPHA`
Commit: `6cb5dfbb4efbfb4113c930a12222de71f21640c7`
OS: `11.0-RELEASE-p10`

**Comment by skarekrow** [comment]
Does the jail not have `vnet` enabled?

**Comment by gronke** [comment]
yes, the jail has vnet enabled

```
# iocage get vnet nginx
on
# uname -aa
FreeBSD foo.example.com 11.0-RELEASE-p10 FreeBSD 11.0-RELEASE-p10 #0: Tue Jun 20 13:44:17 UTC 2017
```

**Comment by skarekrow** [comment]
Meh. If it's that same bug rearing it's damned head again I swear...

I'll check it out later, thanks for the report :+1:

**Comment by joachimmathes** [comment]
I encountered the same issue, because I also use multiple network interfaces. I must admit that I ignored it so far, since the message is only a warning.

An approach could be to attach the bridge device to the address part, like `iocage set interfaces=vnet0:bridge0|192.168.0.1/24`. But that would be an API breaking change, of course. And I don't know, if there are further side effects, I haven't seen yet. But anyway, I think the check `if nic != iface` in https://github.com/iocage/iocage/blob/master/iocage/lib/ioc_start.py#L423 does no longer make sense when it comes to multiple NICs.
