### ISSUE TITLE
Hierarchial basejail feature request

### ISSUE THREAD

**Issue by zenny** [iocage/iocage#194]
It would be nice if hierarchical jails (xN) can be created from a custom base jail  like:

# iocage create hostname=childjail tag=childjail count=N usebase=basejail

which will create 10 childjails from the basejail with hostnames viz. childjail1 to childjailN so that all childjails gets updated when basejail is updated.

**Comment by pannon** [comment]
@zenny just to clarify this, you want hierarchical eg. nested jails in jails or custom basejails?

**Comment by sineer** [comment]
Hi @skarekrow,

I may be wrong but I don't think that's what he wants... I want that though :-)

I think he(she) wants SPARSE jails maybe?

That is what I wanted and I implemented it but still a hack that needs to be improved on and documented.

I didn't know it was called sparse jails until very recently I found out solaris called them that way.

This is what i'm talking about:
https://www.freebsd.org/doc/handbook/jails-application.html

shared read-only zfs root fs for / with a /s dir to mount readable zfs pool(s) such as /var /etc /home...

When you upgrade you just swap / and remount /s finally mergemaster -U and your're good to go.

I did not quite fully understand the idea behind current basejail implementation. I mean I don't really understand how it's meant to be used but I think it's meant to be used more with binary releases of freebsd isntead of from source like I always build my own world...

I hope to cleanup my sparse jail hack and submit a pullrequest for it in a few days.

I'm also working on a solution to sync remote jails using zfs replication now with zrep I think... I want full git-like remote push/pull using zrep over ssh to work with them sparsejails!


However, I would ALSO like true hierarchical jails support (nested jails) and I played with that about a year ago and had it working.. 88chars mount limitation was the biggest issue too. 

It works great with a mix of vnet nosting non-vnet child-jails and I even used that to sandbox say a "mail" jail template that had a child sql jail, www jail and finally one for dovecot/postifx.. I really like hierarchical jails for that... I had them setup as sparse jails too that is my ultimate sandboxing goal: hierachical sparse jails!

p.s. sorry for the long post.

**Comment by skarekrow** [comment]
@sineer Hello :)

Hierarchical jails with basejails is AFAIK not possible since they are multiple datasets, maybe I'm wrong? As for your sparse jail link, that *is* what our basejails do :) We swap out / and do an etcupdate merge on /etc. Nothing needed to be built from world, and we only use freebsd-update to update the initial fetched txz's.

As far as I understand @zenny's feature request, he wants essentially a basejail template that he can batch create jails from. Then he updates the 1 basejail template and it filters down to the rest of the children.

**Comment by sineer** [comment]
I believe what you described is sparse jail not hierarchical (I found out they are called this way like 2 days ago even too I've been using this for years)

What is described in that link from fbsd handbook is sparse jails because it shares (nullfs mount) the same mroot (/) with many jails and mount it readonly. Solaris call it Sparse Zones.

What I don't understand in  current basejail implementation is why does it create/clone all them readonly pools for /usr/bin, /usr/include, /usr/... ($bfs_list) instead of cloning one single readonly root pool with a /s to mount the writable pool(s). I find that creates lots of readonly snapshots for nothing and if you were to use that within a nested jails you'd have to re-mount all that bfs_list within the child jail(s) that would be overkill... Instead I like to see a sfs_list that creates pools for my writable data like /var /etc and /home.

I do clone the "sparse" mroot in my current implementation and set that as readonly after I tweaked it just like the handbook does so that it's ready to host the writable pools using links for /etc, /var ... maybe instead of cloning I should straight up nullfs mount the one instance of the sparsejail like I did in my previous hack now that I think about it you are correct it is how I was able to use the same readonly mroot within nested jails.

Yes, nullfs mount is the key to sparse jails because indeed zfs cannot mount same fs twice even when mounted as readonly. I believe proper sparse jail implementation should nullfsmount /ioc/sparse/mroot into /ioc/jail/UUID/root and create zfs pool(s) for the /ioc/jail/UUID/root/s ... I remember now that worked with hierarchical jails also :-)

**Comment by sineer** [comment]
To clarify, (imho) hierarchical jails is running jails within a jail. It is possible with the proper allow_childsometing flags and sysctl combination... It also used to require a kernel hack to allow using chroot within the jail if my memory is correct.

All kind of neat tricks are possible using sparse jails + hierarchical such that you share the same base system (readonly mroot) with the child jails.

I remember now another neat trick I did was to unmount some jail templates from the host and mount them "live" within a jail then jexec into it to zfs clone that template into a new jail within the jail using iocage as a new zfs thin clone pool owned by the jail! Finally I could unjail the template jail, giving it back to the host and the jailed thin clone kept mounting no problem :-) That was part of my strategy to be able to clone my templates within the child so that I could create somekind of "composite" jails and it was working great! i.e. I had an sql template I "thin" cloned into several child-jails and all them jails shared the same single readonly mroot using nullfs mount!

**Comment by pannon** [comment]
Sparse jails are our basejail concept implemented with ZFS dataset clones instead of nullfs. @skarekrow is overhauling that right now to simplify sparse/basejails.

I think the terminology for basejails originates from Ezjail - basicaly describing nullfs sparse jails.

The hierarchical/nested jails are interesting, there are some challenges there but certainly doable although not sure how many folks require that - possibly Poudriere in a jail (jail in a jail).

**Comment by sineer** [comment]
Hi Peter,

I agree with you sparse jail and base jail are the same idea.

I will be keeping a close eye on skarerow's changes to see how it refactor
current basejail implementation :-)

In my latest experiment I also used thin zfs clone (a single readonly one
for mroot) instead of nullfs mount and I mount my writable pools for the
sparsejail fs (/s) and childs /var, /home and /usr-local. Later I can use
zfs rename to tempoerately relocate the /s sparsejail fs and it's child
somewhere safe, destroy the /root readonly thin clone and replace it with
latest mroot clone finally zfs rename /s in place and restart jail +
mergemaster.

Nullfs mount option is still very much desirable imho... and I bet that is
what our friend Zenny wants :-)

Readonly nullfs mount of /ioc/super/mroot instead of zfs clones mean any
changes to /ioc/super/mroot are reflected in the jails without having to
use zfs to update the clones... This opens up more possibilities also for
different kind of jail setup and would work in a hierarchical jail setup.

Having the ability to thin clone templates within child jails I found was
really a neat way to provision new jails (iocages within iocage) :-)

**Comment by zenny** [comment]
Sorry for entering into discussion a bit late.

§1. I propose to create a possibility to create nested/hierarchical jails so that jails inside jails could be created (useful for production-level development environments with multiple developers)

§2 A sparse jail that can be reproduced in multiple copies with single command so that the update of the base/sparse jail is necessary without requiring to upadate all child jails separately.

Thanks to @pannon, @skarekrow and @sineer for useful inputs. You guys rock! :dancers:

**Comment by skarekrow** [comment]
So we were all right? Heh, great! Well "#1" may not work with our default jails (which are basejails) but I believe you could create a thick jail `iocage create -t` and enable the jailed dataset. Then you can use iocage inside the jail to operate on that dataset. That requires a few other jail properties to be set at creation. Likely all the `allow_mount` ones.

**Comment by skarekrow** [comment]
@zenny this should now be implemented with a combination of `tag=`,`base=`,`host_hostname=` and `count=` :)

The hierarchical jails were already supported using a jailed dataset with iocage inside the jail.

**Comment by saik0** [comment]
Seems to have been broken by f0bb7aa90ab4b7e809a78d0da03af94a9c5f93ac.

Are you planning on using the template property?

**Comment by skarekrow** [comment]
Open an issue with the specific parts that seem broken to you. The `template` property is used yes. You use `istemplate` to specify a jail to become a template. Things have changed quite a bit since this issue was created :)
