### ISSUE TITLE
Please don't close issues so quickly

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#235]
I have lodged a number of issues. Many of them are closed immediately on the assumption that they are not issues at all. I then have to come back, find them (because they are now closed) and comment again, at which point they are seen as actual bugs or things that need to be clarified. I am not opening issues to be a pain, I am doing it to better iocage. When issues are closed immediately it gives the feeling that its more important to close issues than it is to work out why the issue was raised in the first place.

**Comment by xerovis** [comment]
Further to this, when bugs are closed and tagged invalid, its not a great message to be sending. Tagging a bug as invalid is a pretty strong act, especially when they are not invalid. This has happened to me a number of times.

**Comment by pr1ntf** [comment]
You seem to be confusing the terms closed and resolved. We love that you are opening issues to better iocage, don't let the closing of a ticket fool you otherwise. Sometimes we will close a ticket when the information given to us tells us the issue should be closed. We are not resolving the issue when closing, we are simply taking it out of the issue queue. If there is miscommunication, or misinformation, you can always go back to the ticket and reply. Everyone who "watches" the repo on github will see the issue comment, including the iocage team. 

If you are having trouble finding your ticket, there is a wonderful guide to GitHub [search features](https://help.github.com/articles/searching-issues/) you may want to give a once over. Finding an issue by author is as simple as searching `author:xerovis`. [See here](https://github.com/iocage/iocage/search?utf8=%E2%9C%93&q=author%3Axerovis&type=Issues)

As for issue categorization (invalid tagging), please don't take it as an insult or anything negative, it's just how the team likes to put issues into categories.

**Comment by xerovis** [comment]
I flagged this issue because its an issue that hurts developer/tester relationships. No developer wants to see issues raised and no tester wants to see their issues closed immediately or flagged as invalid. Raising issues helps everyone make a better product.

I understand that you guys don't think this has been occurring or that I am misunderstanding your development process. Maybe I don't understand your development process but I do feel like some issues are being closed prematurely - this is one example - https://github.com/iocage/iocage/issues/228

**Comment by skarekrow** [comment]
That issue (#228) was closed because that title hardly described what the issue *was*. When you finally explained it, I renamed it to reflect the problem and then promptly issued a fix. As I have with many of your issues. 

On one hand I do like seeing issues raised, it shows me that people are trying it and it's nice to be able have a sound mind that everything works and whatever may have been broken is no longer the case. It creates a good relationship. 

What doesn't create that relationship is opening duplicates, and not doing any research. Our man page has had the answer to a lot of questions you have asked. In addition, many of your tickets had a tertiary relationship to iocage. I'm happy to help new users get accustomed to a new operating system, but you can't expect me to keep those open on our issue tracker.

It only serves to clutter the space for real issues. Creating concise bug reports that have an accurate title is key to getting attention. When issues are named `iocage destroy` that makes me have to suss out what the real issue is. That is just wasting valuable time. If you had spent a little more time filing the issue ensuring it has an apt title with a descriptive report of your problem, I may have already had the problem solved.

Recent examples that you have filed:
#219 
#214 
#209 
#208 
#204 
#197 

Don't get me wrong, I enjoy that you are trying out our software and filing issues. But those titles aren't helpful. In the future, please name them accurately. Also please don't file non-iocage related questions. Many people have answered FreeBSD related questions on the appropriate forums across the internet. This is not a forum, it is an issue tracker. For iocage. 

What it boils down to is, I answered your questions very quickly and fixed any problems you had very quickly. Opening and continuing discussion in an "issue" like this is disrespectful of all the time I spent assisting you. If you need any help with general questions, try our Google Group, Mailing List or Forum before filing an issue. That helps everybody out.

Thanks,

Brandon

**Comment by xerovis** [comment]
Hi Brandon,

I can see your point in some regards.

1. Some of my questions have been because of documentation issues, where else can I ask a question about something and have it documented for anyone to see? The googlegroup has 6 posts in it, its not particularly active. Google forces you to use your real name and I am not interested in that. The mailing list is not really public and has very few users. github is the most public and easy to use place to do this.

2. I have lodged a couple of duplicate bugs. I did this because I know when in heavy development bugs get lodged, fixed and then can reappear. Also sometimes issues are not seen as issues until a number of perspectives are lodged. I did some of the duplicates knowingly.

3. I was upfront about my skill set in one of the first issues lodged, my job role is to turn software into products/business models. This is where I am coming from when I lodge a bug. I am coming from the perspective of iocage stakeholders that are Users and not OS experts. I do it intentionally so that these types of stakeholders are serviced by iocage. I do this because I know you guys are going to service the OS experts well because that is what you are. I am trying to offer a different perspective.

4. I could use iocage and not lodge bugs but I choose to lodge bugs to help out iocage, the developers and its users. We do not use iocage in any of our environments at all, we may never use iocage. We run two physical servers in the datacenter just for iocage testing, so that I can find bugs and lodge them. We do this because I like where iocage is heading and I want to help.

5. Issue headings are a hard thing to get right for everyone involved. Its not feasible to make the heading massive and the body small. The heading by design is small and the body large. I try to create headings that give the reader the ability to replicate the issue ASAP and in the body I explain where I think the issue is. I am not sure how else to lodge issues.

6. I realise that you guys see things from your expertise/developers perspective and I see it from my own expertise/perspective. I am used to clashing with developers because of the difference in perspective but in the end we are all working for the same goal, bettering iocage.

#219 
The heading was the command that created the error and the body was my thoughts on how iocage could be improved. I am not sure I understand where I went wrong here?
#214 
The heading was the command that created the error and the body was my thoughts on how iocage could be improved. I am not sure I understand where I went wrong here?
#209 
The heading was the command that created the error and the body was a description of the bug. The man page was incorrect. I lodged the bug?
#208 
The heading was the command that created the error and the body was a description of the bug. I am not sure I understand where I went wrong here? The man page was incorrect. I lodged the bug?
#204 
Can see a bit where you are coming from with this issue but it was a user bug in my mind. You should understand that I don't know where you want to take iocage so I am lodging enhancement issues blind.
#197 
Still not sure where I went wrong? This is a bug from my perspective.

Quote - "Our man page has had the answer to a lot of questions you have asked"
I think I lodged two issues that the man page explained and these were early on. I have lodged just as many issues that fix man page problems.

Quote - "many of your tickets had a tertiary relationship to iocage"
From your perspective they do, from my perspective they do not. I am not lodging these bugs because I am a stupid new FreeBSD user, I am lodging them because lodging tickets like this is what I have done for a living for 15 years.

Quote - "I'm happy to help new users get accustomed to a new operating system"
We have been using FreeBSD in production for a year or two. We are well versed in FreeBSD having moved over from 10 years of linux experience. I am not confused on how to use the operating system. I lodge these bugs because these are the questions some of our developers ask about iocage.

**Comment by xerovis** [comment]
Hi Brandon,

I can see your point in some regards.

1. Some of my questions have been because of documentation issues, where else can I ask a question about something and have it documented for anyone to see? The googlegroup has 6 posts in it, its not particularly active. Google forces you to use your real name and I am not interested in that. The mailing list is not really public and has very few users. github is the most public and easy to use place to do this.

2. I have lodged a couple of duplicate bugs. I did this because I know when in heavy development bugs get lodged, fixed and then can reappear. Also sometimes issues are not seen as issues until a number of perspectives are lodged. I did some of the duplicates knowingly.

3. I was upfront about my skill set in one of the first issues lodged, my job role is to turn software into products/business models. This is where I am coming from when I lodge a bug. I am coming from the perspective of iocage stakeholders that are Users and not OS experts. I do it intentionally so that these types of stakeholders are serviced by iocage. I do this because I know you guys are going to service the OS experts well because that is what you are. I am trying to offer a different perspective.

4. I could use iocage and not lodge bugs but I choose to lodge bugs to help out iocage, the developers and its users. We do not use iocage in any of our environments at all, we may never use iocage. We run two physical servers in the datacenter just for iocage testing, so that I can find bugs and lodge them. We do this because I like where iocage is heading and I want to help.

5. Issue headings are a hard thing to get right for everyone involved. Its not feasible to make the heading massive and the body small. The heading by design is small and the body large. I try to create headings that give the reader the ability to replicate the issue ASAP and in the body I explain where I think the issue is. I am not sure how else to lodge issues.

6. I realise that you guys see things from your expertise/developers perspective and I see it from my own expertise/perspective. I am used to clashing with developers because of the difference in perspective but in the end we are all working for the same goal, bettering iocage.

#219 
The heading was the command that created the error and the body was my thoughts on how iocage could be improved. I am not sure I understand where I went wrong here?
#214 
The heading was the command that created the error and the body was my thoughts on how iocage could be improved. I am not sure I understand where I went wrong here?
#209 
The heading was the command that created the error and the body was a description of the bug. The man page was incorrect. I lodged the bug?
#208 
The heading was the command that created the error and the body was a description of the bug. I am not sure I understand where I went wrong here? The man page was incorrect. I lodged the bug?
#204 
Can see a bit where you are coming from with this issue but it was a user bug in my mind. You should understand that I don't know where you want to take iocage so I am lodging enhancement issues blind.
#197 
Still not sure where I went wrong? This is a bug from my perspective.

Quote - "Our man page has had the answer to a lot of questions you have asked"
I think I lodged two issues that the man page explained and these were early on. I have lodged just as many issues that fix man page problems.

Quote - "many of your tickets had a tertiary relationship to iocage"
From your perspective they do, from my perspective they do not. I am not lodging these bugs because I am a stupid new FreeBSD user, I am lodging them because lodging tickets like this is what I have done for a living for 15 years.

Quote - "I'm happy to help new users get accustomed to a new operating system"
We have been using FreeBSD in production for a year or two. We are well versed in FreeBSD having moved over from 10 years of linux experience. I am not confused on how to use the operating system. I lodge these bugs because these are the questions some of our developers ask about iocage.
