### ISSUE TITLE
What is the purpose of the "underscore" folder?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#242]
I noticed there is an underscore folder in the UUID folder for a jail. Why is it an _ instead of something else? It seems this folder is the read/write portion of the jail, is this correct? If so why is there a /usr/ports folder in there? I am pretty sure I didn't create a /usr/ports folder and the folder is blank. I thought the /usr/ports folder was created when running "portsnap fetch update" inside the jail?

**Comment by skarekrow** [comment]
It's an underscore because I didn't want it cluttering up the directory. That's a nice and concise way of essentially saying, "This is our new root". As for the ports folder, yes normally that would be created by `portsnap`. But since we have to mount an overlay into the jail, we need that directory created before hand. It would be much more difficult to do it later when a user wants to fetch ports, as we wouldn't know this and would be unable to create the directory unless they stop the jail and did some invocation.

Hopefully it's not too annoying ;) It's just an empty folder after all.

**Comment by xerovis** [comment]
No its not annoying, just not documented anywhere but now it is.
