### ISSUE TITLE
exec_poststart command not being executing

### ISSUE THREAD

**Issue by pointybeard** [iocage/iocage#251]
This is touched on in issue #250, which is now closed, however I think deserves its own issue.

#### Steps to Reproduce

    iocage create exec_poststart="touch /var/test-file.txt" start=1
    iocage console UUID
    ls -lah /var

#### Expected Output

File `/var/test-file.txt` is created.

#### Actual Output

The file `/var/test-file.txt` has not been created. It is unclear if the command is failing, or just not getting run at all.

**Comment by skarekrow** [comment]
You guys need to read `jail(8)` if you want to use this functionality. Anyways, `post_start` executes in the *systems* environment. So that means you have a test-file in /var. If you want this in the jail, you need to give the complete path to the jail. Since we generate the UUID on creation, you can use a fun trick:
```
iocage create tag=test exec_poststart="/usr/bin/touch /iocage/jails/\$uuid/root/var/hello" start=yes
```
That will create the file where you wanted it. Note that tcsh and csh do not like that syntax. You will need to be in `/bin/sh` or something equivalent for that to work.

**Comment by pointybeard** [comment]
Read the f*&king manual eh? Thanks for pointing out my inability to read.

**Comment by skarekrow** [comment]
:D We all do it, no worries.
