### ISSUE TITLE
iocage exec -U <user> <command> ends up with root environment

### ISSUE THREAD

**Issue by jooize** [iocage/iocage#253]
I'm executing commands to setup jails from outside, and found `iocage exec -U znc znc znc --makeconf` acting strangely (may be unrelated to iocage), but mostly worked around that with `--datadir`. It still somehow changes ownership of the configuration directory—which is a jailed ZFS dataset—to `root:wheel` and fails to write its `.pem` until the second time I change it to `znc:znc`.

However, I found the following behavior:

```
# IOCAGE_ZNC_UUID=`iocage get host_hostuuid znc` && \
curl -Lo /iocage/jails/${IOCAGE_ZNC_UUID}/root/usr/home/znc/znc-push.zip \
https://github.com/jreese/znc-push/archive/master.zip

# iocage exec -U znc znc unzip ~/znc-push.zip
unzip: Failed to open '/root/znc-push.zip'

# iocage exec -U znc znc whoami
znc

# iocage exec -U znc znc env | grep -E 'PWD|HOME|USER|GROUP'
PWD=/root
GROUP=wheel
HOME=/root
USER=root
```

I would expect `iocage exec -U znc znc unzip ~/znc-push.zip` to extract `/usr/home/znc/znc-push.zip` inside the jail, but it aims for `/root/znc-push.zip`.

Is this expected, and in either case how should I do what I want?

**Comment by skarekrow** [comment]
That is unfortunately expected behavior. We just wrap `jexec` and it does the same thing you printed out above. I normally chroot into my jails, which is a valid workaround for you as well:

`iocage chroot UUID|TAG su - USER -c COMMAND` which would give you 
```
root@devbox:~ # iocage chroot exectest su - test_dude -c env | grep -E 'PWD|HOME|USER|GROUP'
PWD=/usr/home/test_dude
USER=test_dude
HOME=/home/test_dude
```
 
instead of:
```
root@devbox:~ # jexec -U test_dude 1 env | grep -E 'PWD|HOME|USER|GROUP'
HOME=/root
USER=root
PWD=/root
GROUP=wheel
```

You can also do this with `exec` though also:
```
root@devbox:~ # iocage exec exectest su - test_dude -c env | grep -E 'PWD|HOME|USER|GROUP'
PWD=/usr/home/test_dude
USER=test_dude
HOME=/home/test_dude
```

I know this is odd behavior, but even if you `jexec -U USER JID /bin/tcsh` and run `env` it *still* gives you the hosts environment. I'm not sure if this is a bug or intended behavior on their part. But as far as our side, we are just wrapping the command for you.

**Comment by jooize** [comment]
Got it, thanks!

**Comment by skarekrow** [comment]
No problem!
