### ISSUE TITLE
regular unplanned hard reboots during iocage usage on 10.2R amd64 & iocage-devel 20150921 from ports

### ISSUE THREAD

**Issue by dch** [iocage/iocage#262]
> unionfs considered harmful in iocage-devel 20150921

Since switching to #8c78110 via `sysutils/iocage-devel`, almost any iocage-related function causes an immediate hard reboot of the box. I've had at least 5 crashes since Monday on a system that has been rock solid for > 2 years. There's nothing recorded in /var/crash/ nor /var/log/messages , dmesg etc. Full h/w diag done on the server overnight was also clean.

This is extremely unstable, effectively unusable in current state. There's nothing in the FAQ like there is for VIMAGE, if indeed unionfs is to blame.

Destroying zroot/iocage, removing `sysutils/iocage-devel`, reverting to `sysutils/iocage`, & rebooting has resolved the issue. `-devel` was certainly stable back in 2015/08/22 when I wrote a nice blog post about it -- what has changed since?

With some care I can test other versions, or try to collect further logs, if there's a way to generate them during crash. How can I help?

**Comment by skarekrow** [comment]
I unfortunately do not control that port. So with that said,  I cannot explain why it's a month out of date. These issues have been fixed,  and unionfs has been great since. Please remember that this is the develop branch,  and thus I won't be putting up a disclaimer every time something doesn't work. The whole point of this branch is for that to happen. Master is our stable branch  and if stability is a concern,  I suggest sticking with that.

Since that's a month out of date it would be very difficult to enumerate every change since. Develop is not guaranteed to work or be stable. So please don't expect that to be the case. Thanks for the blog post though and  you're certainly welcome to try the latest commits but everything is up in the air until we tag a stable release.  No guarantees for migrations between changes made during develop as  they may not stay. 

Caveat emptor ;)

**Comment by dch** [comment]
I'd assumed the project owns the port and would want to know, I can see how that's problematic considering you don't. I'm happy to try master, & will send a patch for bumping the -devel port "upstream" whereever that is. Thanks!

**Comment by skarekrow** [comment]
Appreciate the heads up though! I will add some disclaimer as this should probably be explained.
