### ISSUE TITLE
iocage list - is there a sort order?

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#274]
When I run the command "iocage list" it does not seem like there is any logic to the order in which the jails are listed. When you run jls, the jails are listed by JID.

Some kind of sort order would make thinks much simpler.

**Comment by skarekrow** [comment]
The sort order is by UUID, and that's only because this is how ZFS delivers the information to us. 

```
[brandon@devbox] ~% iocage list
JID  UUID                                  BOOT  STATE  TAG       TYPE
-    0870c0cc-8818-11e5-90f3-d05099728dbf  off   down   test5_1   basejail
-    0890b0b2-8818-11e5-90f3-d05099728dbf  off   down   test5_2   basejail
-    08b06b03-8818-11e5-90f3-d05099728dbf  off   down   test5_3   basejail
-    08d0e625-8818-11e5-90f3-d05099728dbf  off   down   test5_4   basejail
-    08f3a1d0-8818-11e5-90f3-d05099728dbf  off   down   test5_5   basejail
-    188be2f3-8818-11e5-90f3-d05099728dbf  off   down   test      basejail
-    24a96c9b-8818-11e5-90f3-d05099728dbf  off   down   test2     basejail
-    2ef14449-8818-11e5-90f3-d05099728dbf  off   down   test3_1   basejail
-    2f164e8e-8818-11e5-90f3-d05099728dbf  off   down   test3_2   basejail
-    2f3c261a-8818-11e5-90f3-d05099728dbf  off   down   test3_3   basejail
-    2f61ffd3-8818-11e5-90f3-d05099728dbf  off   down   test3_4   basejail
-    2f8e3441-8818-11e5-90f3-d05099728dbf  off   down   test3_5   basejail
-    2fbd81c6-8818-11e5-90f3-d05099728dbf  off   down   test3_6   basejail
-    2fef3da2-8818-11e5-90f3-d05099728dbf  off   down   test3_7   basejail
-    301f84e2-8818-11e5-90f3-d05099728dbf  off   down   test3_8   basejail
-    305191bc-8818-11e5-90f3-d05099728dbf  off   down   test3_9   basejail
-    30857811-8818-11e5-90f3-d05099728dbf  off   down   test3_10  basejail
```

Ideally it would be sorted by TAGs, but that's actually a lot more difficult then it sounds the last time I attempted this. `jls` doesn't have that problem as the jails it shows are only active ones, we show all of them. So sorting by JID doesn't help when there can be jails that aren't running. Or jails that aren't made with iocage.

So really I don't see it worth the time to do. You're totally welcome to try and I'd happily test and merge a PR. But for now, this will be closed as we won't be doing it.

**Comment by xerovis** [comment]
Thanks skarekrow.

"So really I don't see it worth the time to do."

Neither do I, just wanted an answer as I couldn't find it documented anywhere. UUID seems like the best of a bunch of bad options.
