### ISSUE TITLE
Vimage Documentation question

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#279]
The documentation here for Vimage - http://iocage.readthedocs.org/en/latest/networking.html#vimage-vnet is not completely clear, especially the comment, "# plumb interface em0 into bridge0" and what iocage is using the second bridge (bridge1) for. Would it be possible to flesh this documentation out a little further? What is interface em0, is that a reference to the WAN interface or some other interface? What is iocage using the second bridge for? Does iocage use epairs? Why does the iocage documentation differ from this documentation - https://thomaso.me/setup/deploy-configure-vnet-vimage-freebsd-iocage-vps

Its great to see that iocage supports vimage but better documentation would make it much easier to use.

**Comment by skarekrow** [comment]
The documentation is written with 1 interface in mind. In which case, specifying WAN/LAN is not very relevant. The second bridge is used for specifying another vnet interface on a different network. Yes we use `epair(4)`, but that's not very relevant to a user for the documentation. We don't differ from that documentation, since he is only specifying bridge0 his would not be correct. The reason we also differ is that is not a blog post written by us, so you should expect some differences. 

From the manpage for the bridge question:

```
  interfaces=vnet0:bridge0,vnet1:bridge1 | vnet0:bridge0

    By default there are two interfaces specified with their bridge
    association. Up to four interfaces are supported. Interface configurations
    are separated by commas. Format is interface:bridge, where left value is
    the virtual VNET interface name, right value is the bridge name where the
    virtual interface should be attached.

    Default: vnet0:bridge0,vnet1:bridge1
    Source: local
```

Here we tell the user to read more about epair if they have questions:

```
SEE ALSO
  jail(8), ifconfig(8), epair(4), bridge(4), jexec(8), zfs(8), zpool(8),
  rctl(8), cpuset(1), freebsd-update(8), sysctl(8)
```

Any PR's with clarifications are welcome.

**Comment by xerovis** [comment]
"The documentation is written with 1 interface in mind" what purpose does this interface provide? Is it the external interface?

"since he is only specifying bridge0 his would not be correct" In what way is his documentation incorrect?

**Comment by xerovis** [comment]
To add further to this discussion. I think whomever created this page - http://wiki.polymorf.fr/index.php/Howto:FreeBSD_jail_vnet was trying to do what I would like to do.
