### ISSUE TITLE
PC-BSD 10.2 iocage jail to host network connection?

### ISSUE THREAD

**Issue by bobk48** [iocage/iocage#287]
I've looked through the docs for iocage, and cannot find a straight-forward, carefully explained example of how to set up an iocage jail so that you can 1) connect to it via ssh from the host, and 2) ssh connect to it from a home network. The main trouble in the docs, particularly with regard to network connections for an iocage jail is that the lines of code you show are very anecdotal, if that's a good word for them. In other words, there is no completely, step-by-step configuration example that shows a jail connected to host or network. For example, the multi-step docs you show for template and jail package creation are explicit and step-by-step. 
I would like to set up nginx jails as web servers. But the main hurdle for me is connecting the jail to the network. I've tried several approaches, all anecdotally suggested by your docs, but none work. I have a simple home network, with a modem/router, and a single server which the router DHCP assigns an IP address to.
Not to downplay iocage in any way, it is excellent software! With Warden, what I have described above was accomplished in one click, and the typing of a single IP address, like 192.168.0.100.
Please feel free to give as verbose an answer to this question, point me to a more articulate and descriptive set of instructions, or I volunteer to write up the doc if you give me enough info.
Thanks!

**Comment by xerovis** [comment]
If I understand you correctly you just want to create a jail with a network connection? This is easily accomplished by setting the property ip4_addr="bce0|192.168.1.12". If you have a firewall on the host, you will need to setup firewall rules for the jail. Once you have network access, SSHing into the jail is also very trivial. You can console into the jail from the host by running the command "iocage console UUID|Tag". To get the UUID|Tag run "iocage list" to get a list of jail UUID|Tags. 

From what I can gather iocage is not meant to be as simple to use as Warden and this is by design. There are many features available in iocage that allow you to do some very cool things. Simplifying iocage like Warden would take extra development work that someone would need to undertake.

If you need any further help than this, a dot point list of what you are having trouble achieving would be good.

**Comment by bobk48** [comment]
xerovis:
Thanks for your considerate and informative comment!
I tried your suggestion, which in various other forms I had tried before, and here's dot point list of what happened-
* On host, Firewall Manager is letting tcp traffic in and out on port 22. No firewall on the router.
* On host, I ifconfig to see what the inet address is, and also to find the name of the nic. 192.168.0.16, em0. So the sub-network the host is on is 192.168.0, nic is em0
* iocage create tag=net1 ip4_addr="em0|192.168.0.10"
* Done. I start the Jail net1. Get a console into it. Do an ifconfig on Jail net1. inet is 192.168.0.10, nic em0. Looking good!
* ssh to 192.168.0.16 error- ssh_exchange_identification: Connection closed by remote host.
* Ctrl-D back to host. Do an ssh 192.168.0.10,error- ssh_exchange_identification: Connection closed by remote host.
This is not a trivial problem, I am just testing a simple ssh connection between host and jail. I have an app called Fing on a tablet that lets me see IP addresses on my home network. After I do the above dot listed commands, my host is now showing as 192.168.0.10+ It originally was 192.168.0.16.
As I said in my original issue post, I have tried many other procedures, all of them spelled out in the iocage docs online. Even a step-by-step solution to what I just did, which seems to me to be very elementary and commonplace, is not documented in an articulate or explicit way. That is the issue here.
I hope I don't sound too harsh or unappreciative in this comment, my aim is to clarify a simple, straightforward operation in iocage. Please believe me, I am not defending Warden. Just trying to get a basic handle on connecting jails to hos (and then to my home network).
Thanks again for your commentary, I appreciate it greatly, my friend.
Robert M. Koretsky

**Comment by xerovis** [comment]
Glad it worked. Keep plugging away with iocage. You will find that while it feels a little more effort to get working, once it is, you are using production quality software in both the OS and the jail management system. I would recommend using FreeBSD just because its got less bells and whistles to muck things up.

**Comment by bobk48** [comment]
Alas, it didn't actually work! Both 192.168.0.6 and 192.168.0.100 are now mapped to the host nic bge0, and what I thought was logging in from another computer to jail or from host  to jail is just logging into host. So disappointed. The only other option I have at this point is to go through the iocage network docs again, and try to make some effective change in /etc/rc.conf and the sysctl.conf file to create a new nic (em0), and bridge that over to bge0. Then perhaps the iocage set ip4_addr="em0|19.168.0.100" net1 will work. Don't know what else to try.

**Comment by xerovis** [comment]
Clone the loopback interface, give the jails IPs on the loopback and then setup NAT for the jails on the loopback interface.

**Comment by bobk48** [comment]
Sorry, I don't follow that. Going back to Docker on Ubuntu 15.10.
Thanks again for your help!
