### ISSUE TITLE
Please add instructions on how to use the code from Github

### ISSUE THREAD

**Issue by assarbad** [iocage/iocage#291]
Hi,

would you please add some documentation on how to use the `iocage` from the `develop` branch without having to overwrite the one installed on the system or uninstalling the "official" (stable) one?

This would make contributing somewhat easier.

Thanks!

**Comment by pr1ntf** [comment]
Have you tried just running with syntax like `./iocage fetch`?

The actual `iocage` shell script will check for libraries in your working folder first. 
https://github.com/iocage/iocage/blob/develop/iocage#L49

**Comment by assarbad** [comment]
I apologize if opening a ticket offended you in some way. But I was specifically asking for **documentation**. I am still getting acquainted with the source code.

**Comment by skarekrow** [comment]
He wasn't offended :) We just close answered questions. In this case, we don't support having multiple iocage installations like you are asking. You can run it from the git checkout, which may or may not change the `lib/ioc-globals` file since it gets touched each time `iocage` is ran. The best course of action is installing it over the stable one. Especially since a lot of changes we do require complete control of the `iocage` dataset. In this case, having both installed would be detrimental as they are not expecting to be competing.

**Comment by pr1ntf** [comment]
>I apologize if opening a ticket offended you in some way.

???

>But I was specifically asking for documentation.

`iocage` is just a shell script, no need to do any fancy pants building from source code or anything. Everything you need is in the `iocage/` folder. The libraries are in `iocage/lib`.

I don't think we need to document that, it's all right there, but that brings me to my next point:

>I am still getting acquainted with the source code.

Feel free to look around and be sure to check out the [contributing](https://github.com/iocage/iocage/blob/develop/CONTRIBUTING.md) documentation. Also applies to creating documentation :wink:
