### ISSUE TITLE
Update resolv.conf on every start

### ISSUE THREAD

**Issue by urosgruber** [iocage/iocage#297]
Hey! First of all thanks for making iocage reality. And before I open any tickets I would like to ask a question why is there an option to update resolv.conf file on every jail start?

**Comment by skarekrow** [comment]
No problem :) This is a ticket btw ;) But for your question, it's because the user can change it to a custom value after the jail has started. And since we use properties, we can really only properly query and set that `resolv.conf` on that boot.

**Comment by urosgruber** [comment]
I don't know if there is some other way to ask such questions :) Do you mind sending you an email? I have a few other questions that is probably better to ask you directly.

**Comment by skarekrow** [comment]
I was just giving you a hard time :) This way is fine, otherwise we recommend our [Google Groups](https://groups.google.com/forum/#!forum/iocage) as other users may be able to assist. I don't usually have much time. It also allows us to have an archive that some other user would be able to find, instead of everyone emailing us the same questions :)

Hopefully you understand.
