### ISSUE TITLE
Issues after upgrade to 0.9.9

### ISSUE THREAD

**Issue by kdbruin** [iocage/iocage#307]
I've just upgraded to 0.9.9 on FreeBSD 11.0 using the provided package and now I have a number of issues:

- status is always "down" in output of "iocage list" but "jls" shows them running
- tags no longer work so I have to use the UUID

**Comment by kasper5** [comment]
I have the exact same issue. But for some reason one jail still works (emby), this jail has been converted to use *name* instead of uuid. (see in screenshot). I suppose the problem comes from that the zfs dataset under /iocage/jails/* hasn't been renamed from uuid to tag (name), resulting in iocage not finding anything.
![iocage_jails_uuid](https://user-images.githubusercontent.com/11734075/28823189-ab3fad5a-76bc-11e7-8930-4c57ce9fcd6b.png)
![iocage_list_new](https://user-images.githubusercontent.com/11734075/28823235-da0d243c-76bc-11e7-84a6-d40f1fa293a4.png)

I can still use jls and jexec etc so it's not a major problem, but still kinda annoying.

**Comment by skarekrow** [comment]
Hmm, the migration should have moved all your jails to named jails. You guys didn't see any errors or anything?

That's why `state` will be wrong and you have to use UUID. The patch notes clearly state that tags have been dropped for NAME.

You can manually `zfs rename` these datasets in the meantime

**Comment by kdbruin** [comment]
How can I rename the datasets? I get the following error:

`cannot rename 'zroot/iocage/jails/a4a3cfdc': child dataset with inherited mountpoint is used in a non-global zone`

**Comment by skarekrow** [comment]
Can you post a list of your datasets please? Without that I'm just guessing, but you're looking for the `data` dataset under each jail. 

You're going to want to issue `zfs set jailed=off DATASET` for each one of those, then you can rename them. Afterwards set `jailed` to on.

**Comment by kdbruin** [comment]
This is the ZFS datasets for one of my jails:

`# zfs list -t all -r zroot|grep a4a3cfdc
zroot/iocage/jails/a4a3cfdc                                                    305M  68.5G   100K  /iocage/jails/a4a3cfdc
zroot/iocage/jails/a4a3cfdc/data                                               111M  68.5G    96K  /iocage/jails/a4a3cfdc/data
zroot/iocage/jails/a4a3cfdc/data/repositories                                  111M  68.5G   111M  none
zroot/iocage/jails/a4a3cfdc/root                                               194M  68.5G   550M  /iocage/jails/a4a3cfdc/root
zroot/iocage/releases/11.0-RELEASE/root@a4a3cfdc                                 8K      -   355M  -
`

I've tried `zfs set jailed=off zroot/iocage/jails/a4a3cfdc/data` followed by `zfs rename zroot/iocage/jails/a4a3cfdc zroot/iocage/jails/git` but the error remains.

**Comment by skarekrow** [comment]
The jail isn't running, correct? And you have a child dataset under data that may need the property set as well.

**Comment by kdbruin** [comment]
Managed to get the dataset renamed and after changing the UUID in the config file the renamed jail started without problems.

**Comment by skarekrow** [comment]
👍 I think the migration might have failed because you guys had running jails. I can't believe I forgot to check for that. I'm in the process of beating it up harder, hopefully for a 0.9.9.1

**Comment by skarekrow** [comment]
Pushed a fix for this, it won't help you guys I'm afraid, but I'll tag a new release. Thanks for the issue!
