### ISSUE TITLE
iocage basejail children example?

### ISSUE THREAD

**Issue by andrew-azarov** [iocage/iocage#342]
- iocage 1.7.4 (2016/02/17)

Mostly dumb question but how does the basejail work? I mean I read the man and the readme and all I see is how you create the basejail. What's next? How does it nullfs mount into child? I see that basejail is created. I used clone on it and it created a clone but I see no hierarchy where live updates on basejail will apply live updates to all other jails. As I see it's mostly just a clone of each part of jail individually which is not what nullfs mounted basejail is about...

So, am I doing this wrong?

**Comment by skarekrow** [comment]
Good thing these aren't nullfs mounted basejails then ;)

If you want that, the `develop` branch is currently using nullfs for the basejail implementation. 

As to the question of how basejails function in the `master` branch (1.7.4), they *are* zfs clones. You have a jail dataset `POOL/iocage/jails/FULLUUID` which has all the needed r/o datasets mounted under `POOL/iocage/jails/FULLUUID/root/FS`. This allows the basejail to keep any data unique to it in `POOL/iocage/jails/FULLUUID/root` and to reuse the base's FS's to keep up to date.

So if you want those changes to propagate, I would suggest editing the base as all children will inherit the changes. But that's not ideal if the changes are to `/etc` since that is not inherited and neither is `/usr/local`. 

Anything in these ***specific*** locations are inherited from the base:
```
/bin
/boot
/lib
/libexec
/rescue
/sbin
/usr/bin
/usr/include
/usr/lib
/usr/lib32
/usr/libdata
/usr/libexec
/usr/sbin
/usr/share
/usr/src
```

For anything else I would suggest using templates. 

As to the question of clones, clones are not basejails. They are an independent jail who's parent is that basejail. So nothing in that case would inherit to the clones. They are essentially ephemeral, do not use them for long-term if your usecase demands the changes propagate.

Hopefully that helped :)
