### ISSUE TITLE
Clone should support snapshots

### ISSUE THREAD

**Issue by urosgruber** [iocage/iocage#342]
As discussed before I have a scenario where cloning a jail by specifying a snapshot would be very useful. I'm not sure if heaving snapshot option while creating jail from a template is even possible but would help even more. 

Scenario

1.  create a template and make specific changes
2. somehow mark a version of this template
3. automated process is creating jails on demand from a specific template
4. there are some updates needed for this template, so start template, do changes, test if all good etc.
5. create new version (snapshot)
6. update automated process to use new version, upgrade old jails to use latest version
7. destroy old version

I know @rwestlund already give me some idea how to actually use a template so not sure if there is actual need for this. Maybe some guide could benefit with some practical ideas how specific jail type can be used.

Thoughts?

**Comment by rwestlund** [comment]
This would be great.

@gronke and I were discussing some ideas for changing the way templates work a couple days ago and this came up. As mentioned elsewhere, I create multiple templates with a version number in the name and nullfs-mount them into my thin customer jails.

If it were possible to both clone and nullfs-mount (perhaps using .zfs/) from different snapshots of one template jail, then I would not need to create so many templates.

It's important to me that I can use multiple versions of my template at the same time so that I can upgrade my customer jails one at a time.

**Comment by gronke** [comment]
As @rwestlund mentioned, we had a conversation about templates and started with the question what a template really is. As we're still discussing and planning in https://github.com/iocage/libiocage/issues/14, I can't tell yet how exactly this will work out, but a clear update process is clearly a requirement for the feature.

What I can tell though is that the import/export mechanism I had in mind for jails can be used to clone from any ZFS source. A snapshot, tagged with the identifier of the target jail, is automatically created in case it's a dataset. (see [libiocage/lib/Storage.py#L75-L91](https://github.com/iocage/libiocage/blob/f6ef6b352d29335d99fd965d6bdce94f8a65b8f3/libiocage/lib/Storage.py#L75-L91) which is called at creation time)

> If it were possible to both clone and nullfs-mount (perhaps using .zfs/) from different snapshots of one template jail, then I would not need to create so many templates.

@rwestlund Seems possible. We could override [libiocage/lib/JailConfigFstab.py#L138](https://github.com/iocage/libiocage/blob/f6ef6b352d29335d99fd965d6bdce94f8a65b8f3/libiocage/lib/JailConfigFstab.py#L138) via user configuration, so that you could reference a path in`.zfs/snapshots/`.

**Comment by skarekrow** [comment]
I'll mark as enhancement, but unlikely major additions to things will happen anymore here. https://github.com/iocage/libiocage is where changes to fundamentals will happen

**Comment by urosgruber** [comment]
@skarekrow should I move this ticket there or ok to have it here?

**Comment by skarekrow** [comment]
@urosgruber It's a good idea to move it there, I'll close it here
