### ISSUE TITLE
Don't require libucl.so when only working uclcmd is needed

### ISSUE THREAD

**Issue by cloyce** [iocage/iocage#347]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from `iocage`
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `develop` if using the stable release or `master` branch.

This is on current develop from this morning.  You know it's fresh because it requires uclcmd.

If you're going to require stuff that isn't even available as a package, you shouldn't make assumptions about how it will be built.

I built libucl as a static library (because I don't like unpackaged stuff crapping up my system directories, and on FreeBSD /usr/local counts) and built uclcmd against it.  Even so, iocage won't run:

    # ./iocage create tag=testjail
    * Please install all dependencies!

iocage only requires that uclcmd work, and it relies on uclcmd being in the PATH.  So instead of checking on how it might be built and where it might be installed, let's instead just check to see if there's a working copy available.  The diff below does that.

    diff --git a/iocage b/iocage
    index 42aefe4..5e96166 100755
    --- a/iocage
    +++ b/iocage
    @@ -114,7 +114,8 @@ if [ "$(__readonly_cmd "$1")" != "0" ] && [ "$(id -un)" != "root" ] ; then
         exit 1
     fi
     
    -if [ ! -e "/usr/local/lib/libucl.so" ] || [ ! -e "/usr/local/bin/uclcmd" ] ; then
    +uclcmd set -n -u -t string -- foo bar < /dev/null > /dev/null 2>&1
    +if [ $? -ne 0 ] ; then
         echo "* Please install all dependencies!"
         exit 1
     fi

Not entered as a pull request because it's a trivial change.  It works:

    # PATH=/tmp/ucl/bin:$PATH which uclcmd
    /tmp/ucl/bin/uclcmd
    
    # PATH=/tmp/ucl/bin:$PATH ./iocage create tag=testjail
      Successfully created: f1cb4a93-f1d4-11e5-ab92-d05099264f2e (testjail)

It would of course work without PATH fiddling if uclcmd was in /usr/local.  Mine isn't, and won't be.  (It also won't be in /tmp/ucl/bin; it's just there for testing purposes.)

**Comment by skarekrow** [comment]
`uclcmd` requires a version of `libucl` that is not in ports. Hence the requirement. I made the assumption of their location as their submissions in ports will put them there. They will at that point become required packages. 

They won't be built as a static library, and even if they are they will still be in `/usr/local`.

Regardless this is trivial, feel free to submit this as a PR. Otherwise it will likely just stay, because as I've stated for all intents and purposes at this moment the shell version of iocage is finished. This branch will not be merged with master. It's just there to put up my tree incase this decision changes.
