### ISSUE TITLE
Modifying iocage defaults?

### ISSUE THREAD

**Issue by jphackworth** [iocage/iocage#4]
What is the preferred way for modifying iocage defaults?

**Comment by abelbabel** [comment]
Well, I think that it is a common way to provide a config file ...
To not violate "self containing": why not set the defaults in script, check if a config file exists and if it exists, overwrite default values with values in config file?

**Comment by pannon** [comment]
I've tried to simplify as much as possible with iocage, part of this was a doing away with iocage specific config files. All default properties can be overridden at creation time - as @skarekrow already outlined above.

Having said that, the defaults could be saved in ZFS properties, the same way jails are configured. Maybe just add a function to save defaults at iocage setup time in the releases ZFS dataset and later query this instead of the script defaults..

**Comment by abelbabel** [comment]
This might be a solution: after setting default values include config file

    if [ -f /usr/local/etc/iocage.conf ] ; then
      . /usr/local/etc/iocage.conf
    fi

If we mistrust the user, maybe we need this instead:

    if [ -f /usr/local/etc/iocage.conf ] ; then
      grep -E '^[[:alpha:]_]+=".+"$' /usr/local/etc/iocage.conf | while read line; do
        eval $line
      done
    fi

If we only want certain values to be redefinable this gets more ugly.

I haven't tested above lines! Maybe they need minor modifications ...

**Comment by skarekrow** [comment]
I think saving it in ZFS properties could be a good idea. Although a configuration file is certainly easier to verify when you are dealing with a lot of datasets. I thought iocage already did this though? Correct me if I'm wrong @pannon but the idea is you can create a jail and specify the options with iocage, possibly move to a different system and install iocage and everything continues as it left off. No need to worry about transferring a configuration file?

**Comment by pannon** [comment]
Yes that is correct for jails. Jails have their configuration stored in ZFS. The default script options are not though - those are defined in iocage itself. If there is a need to specify custom defaults globally we should consider storing those in ZFS as well.

**Comment by skarekrow** [comment]
I agree.

**Comment by pr1ntf** [comment]
I think there should be a central iocage.conf for iocage wide stuff and defaults, but zfs datasets for per jail stuff like rctl and quota.

**Comment by skarekrow** [comment]
That is my personal feeling as well @pr1ntf.

**Comment by pannon** [comment]
How about saving those defaults in a ZFS dataset `iocage/.conf`?

**Comment by skarekrow** [comment]
And having each text file be the defaults for every jail and one for the
core system?

**Comment by pr1ntf** [comment]
Yes, @pannon, that gets the job done. I'm for it as long as we can set both settings and defaults there.

**Comment by pannon** [comment]
@sineer @abelbabel @jphackworth @skarekrow @pr1ntf this should work now with latest version in development branch.

To save a default property configuration use the `default` keyword instead of the UUID or tagname.

examples:
`iocage set vnet=off default`
`iocage set compression=gzip default`

The examples above will be re-applied when a new jail is created automatically.

**Comment by skarekrow** [comment]
Great work Peter!
