### ISSUE TITLE
"iocage set" does no proper commandline parameter parsing

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#433]
Hi,

with iocage Version 0.9.9.2 09/30/2017 it is possible to do (for example)

`iocage set wallclock=on` or
`iocage set help`

without getting any error about missing jail argument or missing options.

Maybe there are similar issues with other subcommands.

Regards,
abelbabel

**Comment by vendion** [comment]
Your second command `iocage set help` should be `iocage set --help` help is actually a flag for the iocage commands rather than a sub command.

```
iocage set --help
Usage: iocage set [OPTIONS] [PROPS]... JAIL

  Sets the specified property.

Options:
  -P, --plugin  Set the specified key for a plugin jail, if accessing a nested key use . as a separator.
                Example: iocage set -P foo.bar.baz=VALUE PLUGIN
  --help        Show this message and exit.
```
As for your first command as the help text states the you need to give it a name of a Jail to act on, I'm not familiar with iocage enough to know if the `ALL` keyword works for `iocage set` like it does for `iocage get` commands. I can't really test this either as I can't think of a property I would want to set globally across all my jails (if that is what you are hinting at).

An example usage for your example might be:
```
freebsd@Snortra:~ % sudo iocage list
+-----+------------+-------+--------------+------------+
| JID |    NAME    | STATE |   RELEASE    |    IP4     |
+=====+============+=======+==============+============+
| 2   | licensesrv | up    | 11.1-RELEASE | 172.16.1.3 |
+-----+------------+-------+--------------+------------+
| -   | wiki       | down  | 11.1-RELEASE | 172.16.1.2 |
+-----+------------+-------+--------------+------------+
freebsd@Snortra:~ % sudo iocage set wallclock=on wiki
...
```

**Comment by abelbabel** [comment]
@vendion 
Thank you. I had no problem with the usage and I was able to set properties for a jail. The given examples were just for illustration of something that seems to work with iocage, because it does not complain about bad usage, but indeed does not work ...

**Comment by vendion** [comment]
@abelbabel Ah sorry I misunderstood your original message and thought it was more on the actual usage rather than the error output, or lack there of, from trying to use `iocage` in that manner. Feel free to disregard my last message then.
