### ISSUE TITLE
[request] plugins documentation

### ISSUE THREAD

**Issue by cedwards** [iocage/iocage#463]
I'm trying to dig around and find out more about the plugins system, but have had a hard time finding any documentation. Searching RTFD showed nothing.

Is it possible to give a brief rundown on listing, fetching and creating available plugins for iocage?
```
arya ~ # iocage --version
Version	0.9.10 2017/12/22
```

**Comment by skarekrow** [comment]
list locally installed
----
`iocage list --plugins` or `iocage list -P`

List remotely available
----
`iocage list --plugins --remote` or `iocage list -PR`

Fetching and creating
----
https://github.com/freenas/iocage-ix-plugins has that information at the bottom

I'll ping @Mrt134 as he was going to write a page on this sometime, and we'll assign this ticket to him since it's doc related.

Thanks for asking!

**Comment by a-stjohn** [comment]
Just checked the latest version of the docs and information on fetching, listing, and plugins is present. The docs can be found at https://iocage.readthedocs.io/en/latest/
Closing this issue.
