### ISSUE TITLE
iocage is slow at loading requests

### ISSUE THREAD

**Issue by NielsDa** [iocage/iocage#517]
Iocage is slow at starting on my system.
Even the splash screen takes 4 sec to display..
Most commands takes 4 sec. to execute no matter what..
I updated to the newest version of iocage on git hub, did not change anything.
I started to insert print commands to locate where time was spent...
Turned out it was the import of the package 'requests' that is slow.
I have looked at the github project for requests, and found a reference to something related to initialization time.
Tried to pull a newer version of requests, this did not change anything, it might be depending on something else (OpenSLL, crypto, idna) that is slow.
I'm not a Python programmer, but it might be possible to delay the import of requests to when it is actually needed.

Make sure to follow and check these boxes before submitting an issue! Thank you.
- [x ] Supply `iocage --version`
Version 1.0 ALPHA  (Updated it from GitHub some weeks ago)
Running on FreeNAS 11.1 U4
CPU Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
Python 3.6
requests-2.18.1-py3.6.egg-info

- [ x] Supply the commands used, along with any steps to recreate it.
time iocage
4.074u 0.228s 0:04.30 99.7%     5+1047k 8+0io 0pf+0w

time python3 -c "import requests"
3.306u 0.173s 0:03.47 100.0%    5+931k 0+0io 0pf+0w

- [ ] Provide the output from the command you issued.
- [x ] Supply what you expected the result or output to be
I did not expect every command to take 4 sec.
And I did not expect a module only used to download new jail templates (a rare operation) to be responsible for 85% of the runtime.

- [ x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by gronke** [comment]
Your output of `time python3 -c "import requests"` leads to the conclusion that this is an issue with the requests module, not iocage. Have you seen https://github.com/requests/requests/issues/4278#issuecomment-346946444? I recommend to close this issue here and moving the discussion to https://github.com/requests/requests/issues/4315. Please feel free to re-open the issue in case it turns out to be related to iocage nevertheless.

**Comment by NielsDa** [comment]
The question is who should fix this.?
_Iocage_ might be using _request_ different from other applications., since it is used as a cli tool, and not a service that runs for hours. (where initial loading time might not be that important)
_Iocage_ could e.g. implement lazy load of _request_, since often it is not needed at all.
https://forums.freenas.org/index.php?threads/iocage-is-slow-at-loading-request.63109/
https://github.com/requests/requests/issues/4315

**Comment by NielsDa** [comment]
@skarekrow 
I'm I the only one experiencing this slow response of iocage on FreeNAS ?

In this thread https://github.com/requests/requests/issues/4278#issuecomment-346946444
an Raspi can load requests in 0.5 s, my  C2750 (faster CPU) uses 3.3 sec.
This also depends on the python software modules on the system. (e.g cryptography.x509)
Since the FN host come as a fixed 'appliance' I would expect all FN 11.1 users running on C2750 to have the same timing.
And an Intel Atom C2 family CPU is fairly common on smaller FN boxes..

**Comment by gronke** [comment]
> The question is who should fix this.?

The upstream repository (`requests`) should fix it.

> Iocage might be using request different from other applications., since it is used as a cli tool, and not a service that runs for hours. (where initial loading time might not be that important)

I agree, lazy-loading is a great way to mitigate this kind of performance issues for most of the use cases. Sadly Python is not optimized for loading performance at all, which is why I have the impression that switching to a different language (that does not have such big module loading issues) is more suitable at all. Yes, it's partially possible to monkey patch the module loader, but I think this goes a bit too far here.

@skarekrow Would you consider breaking the code pattern of top-importing and gain better startup performance? I think this is reasonable to do in several places (independet of the requests module).

**Comment by skarekrow** [comment]
@gronke We could, but that code style is not very developer friendly. I'm not 100% opposed though.

@NielsDa I've found that RAM and not having fdescfs mounted results in some terribly long execution times.

**Comment by NielsDa** [comment]
I have 16Gig ECC RAM, this should be enugh,
i have fdescfs mounted on the host and inside the jails.
```
df
Filesystem                                                     1K-blocks       Used      Avail Capacity  Mounted on
fdescfs                                                                1          1          0   100%    /dev/fd
```
