### ISSUE TITLE
Improvement - The documentation is unclear about network configuration

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#55]
I was reading through the documentation and I've found its very misleading about the network configuration required for iocage to get the internet acces:

* step 2: it talks about assigning IP to a bridge, but it doesnt talk about creating it before that
* step 4: talks about vnet0 interface but doenst talk about creating it before that, and is unclear wether it should be done in jail or outside it and is confusing, because the example seems to be for a NAT setup
* step 5: talks about adding nameservers to resolv.conf, but doesnt mention it should be done inside the jail (or in base jail, for that matter)
* step 6: talks about exiting from chroot, but doesnt talk about entering it before
* step 7: doesnt really show anything useful
* step 10 and 11: talks about pinging from inside of the jail, but by default, the pings are not allowed inside of the jails

The above points are in relation to the document found here: http://iocage.readthedocs.org/en/latest/help-no-internet.html
In addition to above, it seems like the pages 'Configuring Network Interfaces', 'Non VNET jails (shared IP)' and 'Help! My jail has no Internet connectivity!' could be merged in one, talking in details about NAT and VNET setups, giving real life working examples to follow - currently it is impossible to get networking iocage working while following these docs.

**Comment by zenny** [comment]
If you refer to http://iocage.readthedocs.org/en/latest/real-world.html, it clearly states how to configure host and guest almost step-by-step. Have a look.

**Comment by bartekrutkowski** [comment]
Clearly, I was talking about three other bits of the documentation, but it seems the one you've pasted could also be merged with those three. Also, this one lacks non VNET real life example.

**Comment by zenny** [comment]
Non-VNET example is categorically addressed here, imho: http://iocage.readthedocs.org/en/latest/shared-ip.html. Please check.

**Comment by pannon** [comment]
In a nutshell, yes the docs need fixing - a lot of it was done with only minimal time available. I am happy to accept changes/corrections to it, and probably a lot better if it is done by someone who is experimenting with iocage as I had a development setup and a lot of things were already configured in the process.

Otherwise I can change the docs, but again it is a time issue right now, so it will take a bit longer.

**Comment by skarekrow** [comment]
Right. I will try to set aside some time and see if I can get a VM going and make sure the new user experience from 0 results in a working setup. Currently we are working on a couple other things that iocage needs. Contributions are most welcome.

**Comment by skarekrow** [comment]
Wasn't able to make time this weekend. Did the upgrade function instead. Busy next weekend as well. So it may be a little bit.

**Comment by bartekrutkowski** [comment]
Any chance to get at least VNET complete steps available here? I just had my host crashed because I tried to follow very unclear instructions from the docs on setting up VNET based jail... and most probably messed something up.
I am happy to post patches to the docs, once someone gives me a rough set of instructions to try, test and improve.

**Comment by pannon** [comment]
@bartekrutkowski will clean up the docs for VNET later today.

**Comment by bartekrutkowski** [comment]
It seems that VNET/VIMAGE is very unstable and in fact is not considered production ready, so I think the best thing to do would be to clear the documentation and focus on non VNET setups instead, which are not prone to crashes, since such experience can drive people away from iocage/FreeBSD. That is, until VIMAGE is actually fixed, but it seems that currently that part of code doesnt have 'owner' so fixes arent very likely in nearest future.

**Comment by pannon** [comment]
This is already highlighted in the docs http://iocage.readthedocs.org/en/latest/known-issues.html . Unfortunately it seems that FreeBSD is not suitable for "production grade" network virtualization. It is a bit of a shame really as VNET/Vimage made a debut long before others - and yet failed to gain any traction.

The Linux crowd made some great progress but their isolation is poor and SmartOS truly stole the limelight recently in this space. There will be a tectonic shift in the next 2 years towards containerization and seems that FreeBSD kind off missed that boat already in the networking space.

**Comment by pr1ntf** [comment]
I'm not opposed to this idea, @bartekrutkowski . In my recent dealings with bhyve, I have been using the tap0 way to set up networking. It's basically a shared adapter. 
This is located in 22.4.1. Preparing the Host: https://www.freebsd.org/doc/en/books/handbook/virtualization-host-bhyve.html

**Comment by pannon** [comment]
Still upgrading the docs, it turned out to be a more laborious piece.. will push when ready. Also any suggestions are welcome too, if you'd like to include certain details in the docs.

**Comment by pr1ntf** [comment]
I, myself, have been wrestling with VNET for some time, so I'll give the docs a go with "newb eyes" this week.

**Comment by skarekrow** [comment]
@bartekrutkowski While I agree VIMAGE is not production ready, the only way it can become so is by continued use. Exposing it to workflows. Having no documentation leaves little people willing to test that feature. I know you had trouble with getting VIMAGE setup, but that's really no reason to remove it entirely from the docs. Peter will be looking at the docs and pushing some improvements. If @pr1ntf has any suggestions for him on what should be added or clarified, I'm sure he'd appreciate it. Otherwise I'll be looking at the docs afterwards as well. We just have a lot going on in the project and IRL, so things have been slow on this particular issue.

**Comment by bartekrutkowski** [comment]
At no point I've proposed getting rid of VIMAGE documentation. I simply think that since VIMAGE is faulty as of now (but updates and fixes ARE coming) the best thing for end user would be to clean up and provide extensive documentation around shared IP network topologies available for use with iocage right now, because this is something that works as intended and doesnt cause OS crashes. The VIMAGE related documentation can wait till this functionality withing FreeBSD is fixed and stable.

**Comment by skarekrow** [comment]
Sorry @bartekrutkowski did I misinterpret this? 
"It seems that VNET/VIMAGE is very unstable and in fact is not considered production ready, so I think the best thing to do would be to clear the documentation and focus on non VNET setups instead, which are not prone to crashes, since such experience can drive people away from iocage/FreeBSD. That is, until VIMAGE is actually fixed, but it seems that currently that part of code doesnt have 'owner' so fixes arent very likely in nearest future."

When you say clear documentation do you not mean getting rid of it? The VIMAGE parts work "OK" on a real machines, but I've had extensive issues inside VM's. But I would argue that the shared IP setup needs very little documentation as that is something that not only is very easy to setup but has extensive coverage around the internet. I would suspect that is why we focus on VIMAGE in the first place, since there haven't been many tools highlighting it and thus exposing it's issues as clearly as iocage does.

**Comment by pr1ntf** [comment]
There did seem to be a bit of an emphasis in the docs regarding VNET/VIMAGE when I first looked. However, since I came from ezjail, I was and am still using shared IPs. I just hard code my /usr/local/sbin/iocage to vnet="OFF" and set ip4_addr="XXX.XXX.XXX.XXX" defaultrouter="XXX.XXX.XXX.XXX" at jail creation. 

I have started throwing a few more tweaks into iocage to try and get the "bridge0/tap0" networking (basically shared IP) functioning right. This is how networking is done in the handbook in regards to bhyve networking. https://www.freebsd.org/doc/en/books/handbook/virtualization-host-bhyve.html

VNET/VIMAGE is still something I am trying to learn. I feel it can become very useful in the future in regards to not only FreeBSD jails, but bhyve, and other virtualization solutions. It should stick around.

**Comment by skarekrow** [comment]
No need to hardcode VNET. But if it makes you feel better that's fine. It
doesn't ship with the GENERIC kernel, so it wouldn't by default be used.
From reading the handbook I don't understand the need for tap0 for shared
IP. Can you elaborate on that? The whole point of shared ip is that it
binds to the hosts interface, if you wanted isolation you would use VIMAGE,
correct?

**Comment by pr1ntf** [comment]
Since I am still playing with VNET, it is compiled, but I still want it turned off by default on creation of new jails. 

I was toying with the idea because of bhyve itself. Shared IP with iocage is super easy. Works out of the box practically. On a system where iocage is not the only virtualization solution, the less network setups the better, is all. 

As far as isolation goes, VIMAGE seems to be the best bet at this point.

**Comment by pannon** [comment]
@pr1ntf if you grab the latest develop branch version, you can set a global default for new jails with: `iocage set vnet=off default`

**Comment by pr1ntf** [comment]
That is super handy!

**Comment by pannon** [comment]
@bartekrutkowski the docs are overhauled now, still a WIP but 90% done. Feel free to make any recommendations. We are gearing up for a major release soon 1.6.0 - just merged a ton of things from develop to master. Will be tagging the release when everything is ready (ETA next 2-3 weeks).

**Comment by pannon** [comment]
Closing this as most docs are updated or in WIP now.
