### ISSUE TITLE
new feature: allow to specify an IP address to inherit from the host

### ISSUE THREAD

**Issue by khera** [iocage/iocage#56]
I would like to request the feature that a jail can inherit an IP address from the host. This would be specified the same way as an IP address is currently, but instead of ifconfig alias/-alias on start and stop to provision the IP, it would just verify it exists and then make it visible to the jail. The IP to be shared would be specified in the configuration of the jail, and it would be the responsibility of the administrator to ensure that the IP was aliased or assigned to the specified interface already.

This will allow a jail to share an IP with another jail, so I could for example run a web server inside one jail and a jabber server in another since they use different ports. Another use case would be if the jail only made outbound connections so the IP doesn't need to be unique from the host's IP. It will also reduce the number of IPs I have to buy from my ISP for my server saving me money...

**Comment by skarekrow** [comment]
So I looked into possibly doing the poor man's version of this and just adding the IP to `jail` and not removing the alias, but I'm afraid that wasn't enough. The solution while not as simple as this would have been is still fairly simple though, just created a cloned interface (like `lo1`) and assign ip's to that device. Setup `pf` or something and nat the jails to the world and rdr to the jail's IP, you'll still see the single IP of the host you're using on the outside, since these aren't routable.

A tutorial that should help explain in greater detail then my post: http://kbeezie.com/freebsd-jail-single-ip/

Unfortunately I don't plan to mess with supporting a firewall right now as that is a whole nother can of worms and I believe is best left up to the user.

Thanks!
