### ISSUE TITLE
all sub commands that output something should support the --output-format

### ISSUE THREAD

**Issue by igalic** [iocage/iocage#639]
currently only list supports `-f, --output-format [table|csv|list|json]`

However, this option seems very useful with *all* sub-commands that produce output

`get` seems especially useful
given that in 2.0 it's primarily outputing json, i'm not quite sure why we don't just do **that** ;)

**Comment by gronke** [comment]
The `iocage get` command requires you to specify a single jail by its name identifier (or UUID for legacy jails). If you do the same with list, the output is the same as you would expect here:

```
ioc list -f json <myjail>
```

> given that in 2.0 it's primarily outputing json, i'm not quite sure why we don't just do that ;)

Because it creates edge cases. Get can be either called with a specific attribute or `--all`. Only when combining `--all` with the `--output-format` argument that you suggest would have an effect and I don't see need to explain it to users vs. pointing to `iocage list` that already does it.

**Comment by igalic** [comment]
here's the output of that right now `ioc list -f json j1`
```json
[
  {
    "full_name": "j`",
    "ip4_addr": "",
    "jid": "-",
    "release": "11.2-RELEASE",
    "running": "no"
  }
]
```

`get` however, has that sweet, sweet `-a` option

**Comment by gronke** [comment]
Okay, to get a full list of properties of one jail, this flag can be handy. Let's hold the idea until the migration from libiocage/ioc to this repository is finished.
