### ISSUE TITLE
RACCT support

### ISSUE THREAD

**Issue by ankerstal** [iocage/iocage#670]
Is there any work put in to getting RACCT support back into iocage? There is no big deal to have this outside iocage, but with many jails it becomes cumbersome.

I would like to help with this, but Im not exactly sure where to start. Any pointers would be great.

Thanks.

**Comment by gronke** [comment]
I was not aware that this feature was dropped from iocage/iocage. @skarekrow can you please comment?

Generally speaking of Resource Limits, [libiocage](https://github.com/iocage/libiocage) features them with compatibility for the syntax. You can find detailed usage in the [handbook section about Resource Limits](https://iocage.io/handbook/features/resource-limits/).

Since libiocage supports nested configuration properties, there is movement towards putting all resource limit in it's own namespace - but not before [iocage v2](https://github.com/iocage/iocage/tree/v2) was published and not without compatibility layer.

**Comment by ankerstal** [comment]
Hehe, now Im a bit confused. I was reading the docs on: https://iocage.readthedocs.io/ and using iocage from FreeBSD official repos. So maybe I just need to read the correct docs..

**Comment by skarekrow** [comment]
No this was discussed in https://github.com/iocage/iocage/issues/343 with @gronke a while back. rctl may make the cut later, but it won't be for 1.0.
