### ISSUE TITLE
Problem with ZFS properties and partial config

### ISSUE THREAD

**Issue by thedix** [iocage/iocage#700]
I use the latest version from master.
The problem: unable to set zfs properties for newly created jails:
```
# iocage set quota=20G test1
quota is not a valid property!
```
The problem is caused by [this line](https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_json.py#L1291).
At that moment variable conf has the following content:
`{'allow_raw_sockets': '1', 'basejail': 'yes', 'cloned_release': '11.2-RELEASE', 'host_hostname': 'test1', 'host_hostuuid': 'test1', 'jail_zfs_dataset': 'iocage/jails/test1/data', 'release': '11.2-RELEASE-p4', 'quota': '20G'}`
So conf["template"] == "yes" check fails because there is no such key "template".
And exception is raised "not a valid property".

I think this bug is caused by new partial config for jails.
I'd fix this bug if it were a small typo.
But seems changing full config to a partial config could be a serious issue because there are plenty of places with direct checking config via "conf['varname']".
This bug affects new jails only, old jails created with full config are not affected.

@skarekrow, could you explain reasons to move to partial config?
Yes, it looks nice, but there are some implications:
1. With partial config it is not comfortable to make config changes directly to config.json. For example, I'd like to enable raw sockets for jail and I don't remember the exact variable name. I open config.json, search for "raw", find "allow_raw_sockets", and set it to 1.
2. Default config can be changed in the future versions (yes!). And when migrating from host with older iocage version to a host with newer version (different defaults.json) could lead to all jails change their behavior unexpectedly.
3. As I mention before, there are a lot of places in the code with direct array access to conf. This can be fixed by using some function to get values, but this should be done in the whole code - is it real?

**Comment by skarekrow** [comment]
In this case the bug is a small typo, using just `.get` would fix it. There are unfortunately some spots that may have been missed, and as you noted those have implications. Let's address your concerns here:

1 - Just open the defaults.json to search for that name, or `man iocage`. The idea is to make it easier to tell exactly *what* was changed from the defaults per jail.
2 - That's true, so if you rely on their behavior I'd suggest migrating defaults.json, or setting those properties per jail. I suppose we could use a `create` flag to use "thick" configurations to bypass this behavior, allowing the user to use the defaults(thin configuration) unless they have good reason not too (your use-case)
3 - That is actually handled in https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_json.py#L639 so when the property is accessed the defaults is used if it doesn't exist in the jails configuration. In the case of grabbing all properties to access the conf in many functions, https://github.com/iocage/iocage/blob/master/iocage_lib/ioc_json.py#L613 is used. So in that case it grabs the defaults, and then updates those values with what was specified in the jails configuration. This should cover all use cases.

The bugs that can come from this should primarily affect ioc_json itself, as every other class is using the interface supplied by that. So thankfully the surface area left to hunt for bugs is rather small for this.

**Comment by thedix** [comment]
1. I agree, but IMO searching and editing only one file is more comfortable as you can see all the options you can change, and you change it in place.
2. It would be great to have such option to choose between "thin configuration" and "think configuration". I think "thin configuration" should be by default.
3. I created a pull request #701 to fix this bug. Seems it works, but to be honest this is a quick-and-dirty fix. I see a lot of conf.get("var", "default") calls and I created fix the same way. Suppose a user changes default configuration at defaults.json, so calls like conf.get("var", "default") would be invalid because "default" is hardcoded and not loaded from user's defaults.json. We should think about it. You mentioned json_get_value() and it is ok with handling configuration, but calling it instead of conf.get() would have performance impact since config file is parsed every call.

**Comment by skarekrow** [comment]
Thick configuration will be added tomorrow :)

**Comment by skarekrow** [comment]
@thedix https://github.com/iocage/iocage/commit/abb7ff69d5903dcdc50a6a6adbdf210fd20f1fc0 :+1:

**Comment by thedix** [comment]
@skarekrow Thanks! :)
