### ISSUE TITLE
Jail hostname not being set correctly in `/etc/rc.conf` in stable iocage

### ISSUE THREAD

**Issue by bartekrutkowski** [iocage/iocage#704]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version`

Version	0.9.10 2017/12/22 on FreeBSD 11.2-RELEASE

- [x] Supply the commands used, along with any steps to recreate it.

`iocage create -r 11.2-RELEASE -n somejail`

- [x] Provide the output from the command you issued.

Jail `somejail` being created and started, however in its `/etc/rc.conf` there is incorrect line added: `host_hostname="somejail"`. This is caused by https://github.com/iocage/iocage/blob/0.9.10/iocage/lib/ioc_create.py#L550

- [x] Supply what you expected the result or output to be

As above, but the jail hostname should be properly set in the jails' `/etc/rc.conf` by correct setting line: `hostname="somejail"`.

- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Tried testing that but the devel version doesn't work at all.

**Comment by skarekrow** [comment]
Was fixed last week https://github.com/iocage/iocage/commit/035344e061e6614db03af43ec85a70ca964be86e

**Comment by skarekrow** [comment]
@william-gr any idea why devel doesn't work? Also when how often/up to date is devel?

**Comment by bartekrutkowski** [comment]
@skarekrow that's great, but it doesn't change the fact that latest stable is broken and latest devel doesn't work either. It begs for at least new tag for new stable package and devel package version reverted to some point in master branch where things work.

**Comment by skarekrow** [comment]
@bartekrutkowski I don't control the ports. As for tagging, this issue repo isn't going to keep hundreds of issues open until a new release is tagged ;) The repo tracks master. As far as master is concerned, this is fixed. The stable versions get these fixes as the tags happen, so naming this ticket after stable iocage doesn't really make sense. They're not branched after all.

**Comment by bartekrutkowski** [comment]
@skarekrow so the project doesn't support any stable version at all? How does that do it any good, where what is assumed to be a stable pkg version isn't working, the project refuses to create new tags and even the devel version, that's often avoided because lack of stability and active development doesn't work at all?

**Comment by bartekrutkowski** [comment]
@skarekrow I've ports commit bit, so if you'd create a new tag for stable that works and point me to a master commit that also works, I could update the ports to generate new working packages. As it is, iocage is completely unusable and broken.

**Comment by skarekrow** [comment]
@bartekrutkowski Of course the stable version is supported, I answered you on this ticket didn't I? I'm saying the issue is fixed, I'm not going to just pump out a not yet ready stable version for a harmless rc.conf change. There are *tons* of important fixes that happened, and work is ongoing to get this ready for a 1.0.

I'm aware you have a ports commit, you were the maintainer for legacy after all ;) We've spoken lots! It seems to be a simple dependency problem, @william-gr will take care of. Thanks for the offer

**Comment by bartekrutkowski** [comment]
@skarekrow this harmless `rc.conf` change stops `sshd` from starting at all in the jails created with iocage. Without `sshd` working correctly certain automation tools relying on it (Ansible for example) instead of executing configuration management inside of the jail, execute them on the jail host, damaging its configuration and function. I wouldn't make a fuss about it if it would be harmless indeed.

**Comment by bartekrutkowski** [comment]
@skarekrow do you mean that between `0.9.10` tag and `master`'s latest commit there isn't a place in the src history that could be deemed stable and thus used for a new stable tag? Tagging doesn't need to happen on `master` branch latest commit...

**Comment by skarekrow** [comment]
@bartekrutkowski I'm aware, I've tagged many releases before ;)

Yes that's what I'm saying. That release was to prep for 1.0. Lots of things happened since and lots of churn happened. Look, I'll release when I deem this stable. Ansible breaking is indeed an issue, but a sed command can work around that for now. There are lots of problems like I said. 1.0 will include all the things, and that's hopefully soon.

That will come When It's Ready™
