### ISSUE TITLE
Don't remove aliases on shared networking

### ISSUE THREAD

**Issue by pos42** [iocage/iocage#758]
Hi

I have host on 12.0 release p1 AMD64 (upgrade from 11.2 a week ago) and my jails on 11.2 release p5. I use shared IP and all is working with iocage 0.9.10 except a few things I was waiting for in 1.0 (like jail upgrades...).

So I just upgraded to 1.0 that just came in ports. I then rebuilt all ports.

Now…
At a host reboot the system by itself change my IPv4 address from a /24 to a /32 mask. The host therefor stopped working on IPv4. In /etc/rc.conf the ifconfig_vtnet0 has a 255.255.255.0 mask and it has always worked…. For the host to work I have to manually run ifconfig and set the /24 mask back and also manually run route add default….

And when stopping a jail the whole IPv4 address is wiped from the host.

1.0 is not working as expected.

I reverted to 0.9.10 ad this was working again. Is this a known problem, or am I missing something?

/Peo

**Comment by phyber** [comment]
This appears to be because iocage doesn't trust FreeBSD or the system adminsitrator to manage IP addresses properly, so iocage /always/ removes IP addresses when the jail is stopped. Additionally, when starting a jail it does some extra work to try and see which interface it should prepend onto the `ip[4|6].addr` if none was given, which would result in FreeBSD removing the address on stop if iocage wasn't already doing it. Both of these things seem very wrong.

If FreeBSD was allowed to manage this, everything should "just work".

  - `ip[4|6].addr` in the form of `interface|ip-address[/cidr]` would have FreeBSD configure the `ip-address` on the given `interface` at jail start, and remove it on stop.
  - The simple `ip-address[/cidr]` form would have FreeBSD trust the system administrator to know what they're doing with their IP addressing, so FreeBSD would neither add nor remove addresses from interfaces.

I believe iocage should either:

  - Just let FreeBSD manage things, as documented in `jail(8)`, or
  - Introduce an option so that people can request regular, `jail(8)` style management for their networking.

My personal preference is the former, and I am planning to hack at iocage to make it work as expected. I understand upstream will have concerns over backwards compatibility, so I also plan to try to add an option to make iocage behave the way it currently does (but default it to off).

I am also aware that there may be good reasons for iocage currently behaving the way it does, however, I didn't notice any comments around the code saying why it does this, nor did I see anything on the [readthedocs](https://iocage.readthedocs.io/en/latest/networking.html) page.

**Comment by pos42** [comment]
If using std shared IP, I find it hard to believe it should be "by design" that iocage 1.0 should remove the main IP of the host when shutting a jail down so I lock myself out from the main host because of the IP is wiped from the IP stack.

Sounds like a huge bug to me that share IP cannot be used at all with Iocage 1.0. If I have only one main IP on the host and share it with several jails, an "iocage stop nnn" destroys access to the main host. So shared IP is not possible now.... iocage cannot just assume I do not want the main IPv4 address left on the main host. If I am logged in to the main host with SSH I am thrown out when stopping any jail that share IP with main host.

iocage just became unusable... As said, I reverted to 0.9.10 where it work as it should and is thinking of switch jail software to something else.

**Comment by phyber** [comment]
Yeah. This behaviour makes it impossible to move some ezjail configurations over.
For example, some of my ezjail configurations share my server's internal IP address, others have their own addresses and a bit of nat on a cloned `lo1`. I was very surprised at the iocage behaviour with the shared addresses while I was moving jails over.

I have started a branch [over here](https://github.com/phyber/iocage/tree/networking-behaviour) in an attempt to fix up this behaviour.

Currently, my branch:
  - Bumps the config version in `ioc_json.py` to 17 and adds a `legacy_networking_behaviour` option which defaults to `off`.
  - Modifies `ioc_start.py` and `ioc_stop.py` to hide the iocage networking behaviour behind the `legacy_networking_behaviour` option.

This means that by default, my branch should simply present the user with the standard FreeBSD `jail(8)` networking behaviour, properly allowing configurations where the jail IP address is shared with the host, with other jails, or both.

I have not tested the branch yet as it's late here, but tomorrow I should have some time to check it. If the testing goes well, I'll be fixing up the documentation a little and then submitting a PR at some point.

**Comment by pos42** [comment]
I would not start a branch of the code without a comment from the author of how shared IP should be used in 1.0 without locking yourself out from the main host. To have more iocage code bases would benefit no one in the long run...  The best would be if the 0.9.10 behaviour was put back and the new behaviour (that I do not understand) would be put as a new feature.

 From how I see it "shared IP" support was removed in 1.0 without mentioning it..

**Comment by skarekrow** [comment]
iocage sets up and tears down the IP's for both modes. Shared is simply
implying an alias as it shares the host interface. 0.9.10 "feature" was
actually a bug :D I'd look forward to a PR to see the suggestions in action.
-Brandon

**Comment by pos42** [comment]
> iocage sets up and tears down the IP's for both modes. Shared is simply implying an alias as it shares the host interface. 0.9.10 "feature" was actually a bug :D I'd look forward to a PR to see the suggestions in action. -Brandon
> […](#)

Please enlighten me/us how it is meant to share single IP between host and jail and not lock yourself out from main host SSH session when stopping the jail.

Regards
Peo

**Comment by skarekrow** [comment]
It was never meant to be used in an actual shared context. The name was to imply it's sharing the hosts nic. 

That will be a problem if you're sharing the single IP, in that case I suggest looking into ip4 inheritance instead.

**Comment by pos42** [comment]
I see... But here https://iocage.readthedocs.io/en/latest/networking.html it says Shared IP and not shared nic. 

And it used to work as the link above said.  But I will stay on 0.9.10 until I have time to figure out a solution... I have many VPS:es with just a single IP with jails on them. All stops working with 1.0

**Comment by skarekrow** [comment]
Hmm that's not good at all. Perhaps with @phyber idea we can roll a 1.1 that you and other users you read it that way can upgrade cleanly

**Comment by pos42** [comment]
I have not used FreeBSD for that long, but I have come to really like iocage. And I prefer to continue to use iocage  if the development path of it wont make it to problematic. Also note that extra IPv4 addresses for VPS:es, even if paid for often must be argued for...  web-SSL is no longer a valid justifications as they point to SNI. I doubt that even if I am willing to take the cost for extra IPs, that they will let me. Not if I argue that a software I use has changed behaviour :)

Because of this the upgrade from 0.9.10 to 1.0 was not good for me :)

So I hope you will see this and help us out...

/Peo

**Comment by phyber** [comment]
Hi,

I've been working on my branch of this a little today, and it's now in a working state where `jail(8)` can manage the addition and removal of aliases from a given interface and `iocage` doesn't have to call `ifconfig` at all.

The biggest change to accomplish this is that the config the jail starts with is written out to a file (`/var/run/jail.ioc-{self.uuid}.conf`) after the jail starts. I will probably change this so that the file is written first and call `jail -f /var/run/jail.ioc-{self.uuid}.conf -c` to start the jail instead.

The code is a little sloppy in places at the moment, as I was learning what `jail(8)` was really doing with the networking and just wanted to proof of concept the whole thing. I hope to clean this up over the next few days and present a working PR.

One extra benefit of this is that iocage (rather, `jail(8)`) can now properly destroy aliases of a jail if the config is changed while the jail is running. For example:

Before:
  - `iocage set ip4_addr="lo1|127.0.1.1" jail`
  - `iocage start jail`
  - `lo1` now has `127.0.1.1`
  - `iocage set ip4_addr="lo1|127.0.2.2" jail`
  - `iocage restart jail`
  - `iocage` stops jail and attempts to bring down `127.0.2.2` which doesn't exist on lo1 yet
  - `iocage` starts jail and brings up `127.0.2.2` on `lo1`
  - `lo1` now has an active `127.0.2.2` and an orphaned `127.0.1.1`.

After:
  - `iocage set ip4_addr="lo1|127.0.1.1" jail`
  - `iocage start jail`
  - config that jail was started with written out
  - `lo1` now has `127.0.1.1`
  - `iocage set ip4_addr="lo1|127.0.2.2" jail`
  - `iocage restart jail`
  - `iocage` stops jail via config we wrote out when it was started
  - `iocage` (really `jail(8)`) correctly brings down `127.0.1.1` as listed in the config
  - `iocage` starts jail, bringing up `127.0.2.2` on `lo1`
  - `lo1` now only has the active `127.0.2.2` and no orphaned addresses.

Obviously, as we're letting `jail(8)` do all of the heavy lifting, the case where the system administrator is managing addresses on interfaces via `/etc/rc.conf` is now supported simply by specifying `ip4_addr=192.168.1.1` or similar without specifying an interface. This allows for multiple jails sharing a single address with each other or the host.

**Comment by phyber** [comment]
I forgot to mention above, but the original `iocage` behaviour is hidden behind a configuration flag called `legacy_networking_behaviour` (bad name, I will likely rename this to `iocage_managed_networking` or similar). However, I am _very_ tempted to remove it and let `jail(8)` manage the network addresses. This would let a lot of networking questions simply be answered by the FreeBSD documentation as `iocage` wouldn't be doing anything special.

**Comment by dgeo** [comment]
Didn't test this, but I'd vote happily d'or @phyber's way if there is any vote...

Relying on jail(8)'s behaviour seems a very good idea IMHO !

**Comment by pos42** [comment]
> Hi,
> 
> I've been working on my branch of this a little today, and it's now in a working state where `jail(8)` can manage the addition and removal of aliases from a given interface and `iocage` doesn't have to call `ifconfig` at all.
> 
> The biggest change to accomplish this is that the config the jail starts with is written out to a file (`/var/run/jail.ioc-{self.uuid}.conf`) after the jail starts. I will probably change this so that the file is written first and call `jail -f /var/run/jail.ioc-{self.uuid}.conf -c` to start the jail instead.
> 
> The code is a little sloppy in places at the moment, as I was learning what `jail(8)` was really doing with the networking and just wanted to proof of concept the whole thing. I hope to clean this up over the next few days and present a working PR.
> 
> One extra benefit of this is that iocage (rather, `jail(8)`) can now properly destroy aliases of a jail if the config is changed while the jail is running. For example:
> 
> Before:
> 
> * `iocage set ip4_addr="lo1|127.0.1.1" jail`
> * `iocage start jail`
> * `lo1` now has `127.0.1.1`
> * `iocage set ip4_addr="lo1|127.0.2.2" jail`
> * `iocage restart jail`
> * `iocage` stops jail and attempts to bring down `127.0.2.2` which doesn't exist on lo1 yet
> * `iocage` starts jail and brings up `127.0.2.2` on `lo1`
> * `lo1` now has an active `127.0.2.2` and an orphaned `127.0.1.1`.
> 
> After:
> 
> * `iocage set ip4_addr="lo1|127.0.1.1" jail`
> * `iocage start jail`
> * config that jail was started with written out
> * `lo1` now has `127.0.1.1`
> * `iocage set ip4_addr="lo1|127.0.2.2" jail`
> * `iocage restart jail`
> * `iocage` stops jail via config we wrote out when it was started
> * `iocage` (really `jail(8)`) correctly brings down `127.0.1.1` as listed in the config
> * `iocage` starts jail, bringing up `127.0.2.2` on `lo1`
> * `lo1` now only has the active `127.0.2.2` and no orphaned addresses.
> 
> Obviously, as we're letting `jail(8)` do all of the heavy lifting, the case where the system administrator is managing addresses on interfaces via `/etc/rc.conf` is now supported simply by specifying `ip4_addr=192.168.1.1` or similar without specifying an interface. This allows for multiple jails sharing a single address with each other or the host.

Regarding the last 2-3 sentences... This is how it works in 0.9.10. Sounds good to me :)  Specifying "ip4_addr=192.168.1.1"  in 0.9.10, the main interface is untouched when stopping the jail. Specifying "ip4_addr=vtnet0|192.168.1.1" in 0.9.10 where 192.168.1.1 is on the main host, the ip is destroyed on main host when stopping jail.

(I guess it is here @skarekrow mean it is a bug and ip should have been removed on both cases on 0.9.10)

B t w... Good to avoid orphaned IPs...

**Comment by skarekrow** [comment]
This is now addressed thanks to @phyber, and will be in 1.1.

**Comment by rosjat** [comment]
hi, i know its closed but it seems i got the issue still in 1.2 on freebsd 12.2. I might do it wrong , just getting used to the whole thing so i am still in the learning process here.

But after a reboot my NIC isnt working on the host system.

cheers

MArkus
