### ISSUE TITLE
Replace 'chroot' suggestions in documentation

### ISSUE THREAD

**Issue by kpfleming** [iocage/iocage#763]
In #542 the `chroot` command was marked as deprecated in favor of `exec` and `console`, but there are still quite a few references to it throughout the documentation in the `doc` directory. I'm happy to send a PR to replace all of them if there's any consensus on what they should be replaced with...

**Comment by skarekrow** [comment]
I think it depends on the context, but I would say that most if not all situations can be replaced with `exec`.

**Comment by kpfleming** [comment]
The one in `templates.rst` is going to be tricky, because it's a suggestion for modifying the content of a template, but `exec` requires starting the jail which can't be done with a template... and I don't think the `chroot` method would have worked either since the template dataset is set to read-only. I suspect the only way to fix that one is to remove it, and leave the suggestion for converting the template back to a normal jail in order to modify it.

**Comment by gronke** [comment]
@kpfleming this issue with Templates was discussed with @skarekrow a couple of weeks ago. Turns out, it's one of the reasons why libiocage is no longer part of the iocage project.

This project moves jails from the `jails` to `templates` dataset when turning them into templates. As soon as a jail was created from a template, it is no longer possible to turn it back into a jail. (see https://github.com/libiocage/libiocage/issues/551#issuecomment-430959716)

Therefore libiocage marks templates as such from the jails configuration rather than moving their dataset. On the other hand it is necessary to return to GUIDs for jail storage locations, as deletion of templates requires the following procedure:

### Template deletion
When deleting a template, check if there are jails existing that have been created from them. If so (1), mark the template as deleted, otherwise delete the template.

### Jail deletion
When deleting a jail, check if it was created from a template. When the template has been marked as deleted and this jail is the only child of the template, delete it as well.

**Comment by skarekrow** [comment]
> The one in `templates.rst` is going to be tricky, because it's a suggestion for modifying the content of a template, but `exec` requires starting the jail which can't be done with a template... and I don't think the `chroot` method would have worked either since the template dataset is set to read-only. I suspect the only way to fix that one is to remove it, and leave the suggestion for converting the template back to a normal jail in order to modify it.

Perhaps the best way to move forward with that snippet is to just remove it. As changing templates would unintuitively make a user expect the changes to trickle down to jails which is not the case. As it's just a parent of a snapshot.
