### ISSUE TITLE
will `iocage get all myjail` come back ?

### ISSUE THREAD

**Issue by dgeo** [iocage/iocage#8]
Currently working on an ansible iocage module, what would be the recommended way to get all properties for a jail ? reading config.json ? `import iocage` ?

Thank you for this great rewrite !

**Comment by skarekrow** [comment]
I'll add that right now, give me a bit :)

**Comment by skarekrow** [comment]
So if you're doing this in python, you will want to `from iocage.lib.ioc_json import IOCJson` and then call `IOCJson("/the/path/to/the/top/level/jail/dataset).get_prop_value("all")` which will return you an JSON object. 👍 

Otherwise `iocage get all JAIL` will work too. You can split on `:` as it will be in the format `prop:value`.

Thanks for requesting this!
