### ISSUE TITLE
[Feature Request] Ability to turn services on during creation

### ISSUE THREAD

**Issue by ghost** [iocage/iocage#838]
It would be nice if I could run something like `iocreate create -r 12.0-RELEASE --name foobar boot=on sshd=enable` to enable any of the default services that come with freebsd.

**Comment by skarekrow** [comment]
That’s a great idea!

**Comment by ghost** [comment]
I would love this to be my first commit and be able to help the project. I haven't coded in python in a few years but I'm confident I can do the job if you could just point me in the right direction on what files to look into?

**Comment by skarekrow** [comment]
I’d like to see a PR that has a services flag that passes a set of services to the lib which calls sysrc service_enable=YES so we can keep this flexible. It will be slightly complex, but should be doable if you’re a little rusty with python.

**Comment by skarekrow** [comment]
@gregf More specifically here are the relevant files for you:
https://github.com/iocage/iocage/blob/master/iocage_cli/create.py#L85 you'll want to add a services flag here

https://github.com/iocage/iocage/blob/master/iocage_lib/iocage.py#L522 and then a services variable that will be None, check afterwards if None then set it to a list (security measure)

Later on in that file you can iterate on that list if it was supplied and we can call sysrc to enable those settings.

I see the syntax looking like this: `iocage create -n foo -r 11.2-RELEASE --services sshd,nginx,foo,bar,baz` and then we can split that on commas to iterate on. That way users can supply packages to be installed and services to be enabled afterwards instead of just the default services FreeBSD ships.

Hope that helps!
