### ISSUE TITLE
Thoughts about basejails and clones

### ISSUE THREAD

**Issue by An-tonio** [iocage/iocage#863]
Hi, I'm moving from iocage_legacy to new iocage.

I was a fan of basejails and his way of create simple jails with nullfs mounts. Now with new iocage version it seem similar but not exactly because the use of zfs clones.

On long term this can cause disk space lost and a mess with snapshots dependencies. In this link you can read about the possible related problem of using clones for basejails in more technical detail:

https://jrs-s.net/2017/03/15/zfs-clones-probably-not-what-you-really-want/

Initially, clones can be "cheap" but in long term, moreover after a release upgrade, we can start to loose a lot disk space if we have a lot of jails.

I'm missing something ? What do you think ? Why not create basejails as before without clones ?

Thanks

**Comment by skarekrow** [comment]
Clones were really chosen for speed. The divergence for clone jail basejails should be minimal, really conf files and whatever you install. Since they switch bases. But I'll change the default to be a thickjail with basejails, as it's not intuitive that these things would be applicable to them on upgrade (IE: Destroying an old RELEASE)
