### ISSUE TITLE
iocage list shows wrong RELEASE 

### ISSUE THREAD

**Issue by gerritche** [iocage/iocage#872]
Minor glitch

- [x] Supply `iocage --version`
Version	1.0 RELEASE 2018/12

- [x] Supply the commands used, along with any steps to recreate it.
Version	1.0 RELEASE 2018/12

- [x] Provide the output from the command you issued.
+-----+--------------+---------+---------------------+-------------+
| JID |    NAME    | STATE |   RELEASE    |    IP4        |
+===+========+======+==========+========+
| -     | nextcloud  | down  | 11.2-RELEASE | 10.1.1.20 |
+-----+--------------+---------+---------------------+-------------+
| 1    | nextcloudJ | up      | 11.2-RELEASE | 10.1.1.10 |
+-----+--------------+---------+---------------------+-------------+

- [x] Supply what you expected the result or output to be

nextcloudJ is on FreeBSD 12.0-RELEASE-p2 GENERIC

- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

not done

**Comment by skarekrow** [comment]
It reads the `release` property, which should be updated on upgrade. Lots have improved in `upgrade` since 1.0-RELEASE. Please upgrade, in the meantime you should manually change the `release` property` in the `nextcloudJ`'s config.json to `12.0-RELEASE-p2`.

Out of curiosity, perhaps the upgrade actually failed? What does `iocage exec nextcloudJ freebsd-version` show?

**Comment by gerritche** [comment]
Sorry for the delay. Update failed unless I did as you suggested and changed the config.json file.

$# sudo iocage exec nextcloudJ freebsd-version 
12.0-RELEASE-p3

iocage list now shows the correct RELEASE tag.
