### ISSUE TITLE
iocage pkg confirmation prompt gets lost

### ISSUE THREAD

**Issue by saper** [iocage/iocage#889]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
     Version	1.0 RC 2018/11

Confirmed with

    Version	1.2 BETA

(git master as of a09857be4f3ef411d0ffd08d4b49fb7267ae7cf8)
- [X] Supply the commands used, along with any steps to recreate it.
https://gist.github.com/7cdc86d3f004adc06294cbd6d232fee9

      # iocage pkg basic install ca_root_nss

- [X] Provide the output from the command you issued

````Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
````
(nothing happens)

- [X] Supply what you expected the result or output to be

````Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	ca_root_nss: 3.42.1

Number of packages to be installed: 1

Proceed with this action? [y/N]: 
````

- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

Just tried a09857be4f3ef411d0ffd08d4b49fb7267ae7cf8

`iocage pkg basic remove` is affected as well.

Workaround: always use `iocage pkg basic install -y` or `iocage pkg basic remove -y` or just use `pkg -j jailnumber` directly.

**Comment by jaredjennings** [comment]
`iocage pkg` uses the same mechanism to execute `pkg` as `iocage exec` uses to execute arbitrary commands inside the jail. The problem is that that mechanism is not built for use with interactive commands. To wit, `[consume_and_log](https://github.com/iocage/iocage/blob/e94863d4c54f02523fb09e62e48be7db9ac92eda/iocage_lib/ioc_common.py#L901)` checks whether blocks of output end with `'\n'`, and doesn't do anything with them if they don't. The `pkg` confirmation prompt, of course, does not end with a newline. `pkg` also prints out dots without newlines as a progress indicator, which may get swallowed; but probably no one would really notice.

When I changed `consume_and_log` so it wouldn't care about newlines, and would process every block of output, not only did I get the full expected pkg output, but also a bunch of empty lines were printed out. It seems that whatever ensuing code actually gets the pieces of output from `consume_and_log` to stdout/stderr (likely `logit`, but I haven't followed that thread) expects to put out a newline at the end of each piece of output. This makes sense in a log, where neither interactivity in general, nor pieces of output shorter than a line in specific, are expected.

Perhaps `iocage pkg` should always supply `-y` to `pkg`. This could be surprising and lead to accidental changes; so perhaps further `iocage pkg` should always take a snapshot first. But this may not be enough: what if a package upgrade causes changes to be made in a remote database, for example?

Or perhaps the requirement to log output of commands run by `iocage exec` is not strong enough that it should break `iocage pkg`. In this case `iocage` would not need to process the output, and could hand stdin, stdout and stderr directly to the executed command. I can't make that call.

Or perhaps `iocage pkg` should act differently than `iocage exec`. Even if most command output should be logged, the output of `pkg` is... more screeny than it is loggy. There is some machinery in there about `interactive` vs. not; I haven't chased that all the way down. Keeping looking.

**Comment by saper** [comment]
Thank you for the detailed explanation what happens. I ran into this immediately when evaluating iocage for myself first time, I was wondering - how iocage users are doing this if things like `iocage pkg` do not work as expected?
