### ISSUE TITLE
Interface dependent default gateway does not make sense

### ISSUE THREAD

**Issue by pmhausen** [iocage/iocage#900]
- [X] Supply `iocage --version`
Version	1.0 RELEASE 2018/12
- [X] Supply the commands used, along with any steps to recreate it.
Create a jail with vnet0/epair0b and vnet1/epair1b, assign IPv6 address to epair0b and ipv4 address to epair1b:
```
iocage set ip6_addr="vnet0|2a00:b580:8000:12:fc98:afb2:b6df:1b1f" vpro0434
iocage set ip4_addr="vnet1|192.168.205.123/24" vpro0343
```
Try to add default routes for IPv4 and IPv6:
```
iocage set defaultrouter="192.168.205.196" vpro0434
iocage set defaultrouter6="fe80::12%epair0b" vpro0434
```
- [X] Provide the output from the command you issued.
No error when the command is run.
- [X] Supply what you expected the result or output to be
When the jail is started it should have a default gateway for each of the protocols. It doesn't for IPv4.
- [X] Checked that the problem has not already been fixed on `master` if using
 a stable release.

The problem lies with this part of `ioc_start.py`:
```
        if ipv6:
            ifconfig = [iface, 'inet6', ip, 'up']
            # set route to none if this is not the first interface
            if iface.rsplit('epair')[1][0] == '0':
                route = ['add', '-6', 'default', defaultgw]
            else:
                route = 'none'
        else:
            ifconfig = [iface, ip, 'up']
            # set route to none if this is not the first interface
            if iface.rsplit('epair')[1][0] == '0':
                route = ['add', 'default', defaultgw]
            else:
                route = 'none'
```

May I ask what the reasoning behind this is? Routing table entries in general are *not* interface specific but global to a host (or jail in this case). One can add a scope explicitly for IPv6 as we do in our example, especially when using link-local addresses for the IPv6 default gateway. If a global unicast address is used, no scope is necessary.

IMHO this code does not make sense. iocage should perform `route add default` for the jail in question with the data provided by the admin and no arbitrary checks.

Kind regards,
Patrick

**Comment by sonicaj** [comment]
Thank you @pmhausen for reporting this. I have added a fix for this here - https://github.com/iocage/iocage/pull/914, would it be possible if you could maybe test this fix ?
I unfortunately don't have ipv6 configured in my local network.
Please let me know if it would be possible, thanks again!

**Comment by sonicaj** [comment]
ping @pmhausen

**Comment by pmhausen** [comment]
I have to talk to my team members if and how we can actually test this. We do not have a test environment for iocage. As long as the fix is not in the FreeBSD port or FreeNAS ...

I'll get back to you ASAP.

**Comment by sonicaj** [comment]
Hello @pmhausen. I can help you set up iocage with my changes, I have closed the above referenced PR because of conflicting branch names we use internally - this is the new PR for this issue - https://github.com/iocage/iocage/pull/922.
Please let me know if you would like my assistance. We for obvious reasons don't want to merge this to master before being sure that the changes work as desired for ipv6.
Thank you

**Comment by sonicaj** [comment]
ping @pmhausen

**Comment by pmhausen** [comment]
Handed over to @joachimmathes who will test it in the next couple of days.

**Comment by joachimmathes** [comment]
Testing begins...

**Comment by joachimmathes** [comment]
I've tested pull request #922 (NAS-101350) in our environment successfully. The routing for IPv4 and IPv6 is working. Thanks for fixing this. :+1:

I know this leaves the scope of this issue, but on `iocage start` I stumbled upon a `Malformed fstab` error, which was raised by the `__validate_fstab__`-method. Our fstabs contain empty lines, comment lines and space separated line elements. This is important for us, since it improves legibility a lot. So, updating iocage from 1.0 is going to break hundreds of our productive systems. I've seen #888 and read the commit messages. But can you or @skarekrow elaborate on why you introduced this restrictive syntax for fstabs. Thanks in advance.

**Comment by skarekrow** [comment]
@joachimmathes File a new issue since this would be an enhancement. Currently iocage does these things because it expects total control of the fstab of the jail. As it's the one managing it. But I don't think it's unreasonable to want a comment flag to the fstab command, along with wanting to comment and use line breaks/spaces for legibility.

**Comment by pmhausen** [comment]
Hi!

> Am 09.05.2019 um 19:54 schrieb Brandon Schneider <notifications@github.com>:
> 
> @joachimmathes File a new issue since this would be an enhancement. Currently iocage does these things because it expects total control of the fstab of the jail. As it's the one managing it. But I don't think it's unreasonable to want a comment flag to the fstab command, along with wanting to comment and use line breaks/spaces for legibility.

Does it? Oops! :-) What#s your idea about automated management
and deployment of jail fstabs? Currently we use ansible to simply
deploy /iocage/jails/foo/fstab and that’s that.

Calling `iocage fstab` breaks idempotency. Now, if you would provide
an iocage ansible module … ;-)

Kind regards,
Patrick
-- 
punkt.de GmbH			Internet - Dienstleistungen - Beratung
Kaiserallee 13a			Tel.: 0721 9109-0 Fax: -100
76133 Karlsruhe			info@punkt.de	http://punkt.de
AG Mannheim 108285		Gf: Juergen Egeling

**Comment by skarekrow** [comment]
ENOTIME :)

**Comment by skarekrow** [comment]
@pmhausen https://github.com/iocage/iocage/pull/929 will address the fstab issues
