### ISSUE TITLE
Versioning scheme misleading

### ISSUE THREAD

**Issue by shivno** [iocage/iocage#96]
A full rewrite seems worth more than 0.9.6->0.9.7. And the old one is 1.7.6. This probably confuses some people. Maybe call it 2.x or iocage2?

**Comment by shivno** [comment]
as i thought a bit about it, most people will install via pkg/ports. i think "rewrite" in the description would suffice. or change 1.7.6 to have "legacy" in description

**Comment by skarekrow** [comment]
A full rewrite did not happen between 0.9.6 and 0.9.7.

The old versioning scheme is indeed confusing as the two ports coexist currently. That won't be the case much longer, and the syntax to get the version has changed between the two. 

So that will be the clarification needed if/when the versions overlap. I've been suggested 2.x which I felt didn't properly explain this is a beta and isn't quite ready. 1.0 should be. iocage2 implies the same thing in my opinion. I have also been suggested iocage-ng, which I'm not a huge fan of. Unless we're talking TNG, I don't like using even *more* words.

The repo is titled `iocage_legacy`, which I feel explains the situation. In my mind, `iocage` is a continually evolving process, and minus a few syntax differences, it's largely the same to the user. I don't feel that merits a new name, and if I had it my way it would have been name `iocage` in ports as well, but python ports just aren't named that way.

Thanks for the question, I hope my reasoning makes sense!

**Comment by shivno** [comment]
Thanks for you thorough explanation. As i said name is ok, changing the pkg description a bit would be great, eg "FreeBSD jail manager rewritten in Python".

**Comment by skarekrow** [comment]
That language would suggest that `iocage` is a Python rewrite of some other jail manager. Instead of being a rewrite of itself, and that is a much less important distinction the longer this project exists. Eventually nobody will remember the old project and will associate the name `iocage` with the rewrite. Much like `Firefox` will still be called `Firefox` when they implement their servo rewrite.

`iocage` is `iocage` no matter the language in my book, and let's say it gets rewritten again (oh god, please not again), it would start to look silly to see "FreeBSD jail manager rewritten in Python now rewritten in Rust" or something.

I'm not trying to be dismissive of your proposal or anything, but I really don't intend to change the wording regarding that status. Unless it becomes a major issue down the line, in which case a full name change is a more apt decision in my book.
